In [295]:
import math
import collections
import requests
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
import matplotlib.pyplot as pp
import csv
import json

%matplotlib inline


from nba_api.stats.endpoints import playercareerstats

from nba_api.stats.endpoints import leaguegamefinder
from nba_api.stats.static import teams

import pickle

In [296]:
nba_teams = teams.get_teams()
msList=list()
with open('NBA_Player_IDs.csv', 'r') as f:
    csvReader=csv.reader(f,delimiter=',')
    for row in csvReader:
        #print(row)
        msList.append(row)
nbaIds={}
BBRIds={}
for line in msList:
    nbaIds[line[4]]=line[6]
    BBRIds[line[0]]=line[2]

with open('scoringLeadersLystALL.pkl', 'rb') as f:
    scoringALL = pickle.load(f) # deserialize using load()

In [297]:
tmpCarreer = playercareerstats.PlayerCareerStats(nbaIds['Jayson Tatum'])
nameTitle='Player_Name'

df = tmpCarreer.get_data_frames()[0]
df.insert(0,nameTitle,'Jayson Tatum')

#df['Player_Name'] = 'Jayson Tatum'
df

,Player_Name,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,Jayson Tatum,1628369,2017-18,00,1610612738,BOS,20.0,80,80,2443.0,...,0.826,50,352,402,128,83,58,114,170,1112
1,Jayson Tatum,1628369,2018-19,00,1610612738,BOS,21.0,79,79,2455.0,...,0.855,70,407,477,168,84,57,122,168,1243
2,Jayson Tatum,1628369,2019-20,00,1610612738,BOS,22.0,66,66,2265.0,...,0.812,64,396,460,200,93,57,155,136,1547
3,Jayson Tatum,1628369,2020-21,00,1610612738,BOS,23.0,64,64,2290.0,...,0.868,50,422,472,276,75,31,171,122,1692
4,Jayson Tatum,1628369,2021-22,00,1610612738,BOS,24.0,76,76,2731.0,...,0.853,85,524,609,334,75,49,217,174,2046
5,Jayson Tatum,1628369,2022-23,00,1610612738,BOS,25.0,74,74,2732.0,...,0.854,78,571,649,342,78,51,213,160,2225
6,Jayson Tatum,1628369,2023-24,00,1610612738,BOS,26.0,74,74,2645.0,...,0.833,67,534,601,364,75,43,188,145,1987

In [298]:
tmpCarreer = playercareerstats.PlayerCareerStats(nbaIds['Jaylen Brown'])
nameTitle='Player_Name'

df1 = tmpCarreer.get_data_frames()[0]
df1.insert(0,nameTitle,'Jaylen Brown')

#df['Player_Name'] = 'Jayson Tatum'
df1

,Player_Name,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,Jaylen Brown,1627759,2016-17,00,1610612738,BOS,20.0,78,20,1341.0,...,0.685,45,175,220,64,35,18,68,142,515
1,Jaylen Brown,1627759,2017-18,00,1610612738,BOS,21.0,70,70,2152.0,...,0.644,66,280,346,114,70,26,124,181,1017
2,Jaylen Brown,1627759,2018-19,00,1610612738,BOS,22.0,74,25,1913.0,...,0.658,65,248,313,100,69,32,99,186,964
3,Jaylen Brown,1627759,2019-20,00,1610612738,BOS,23.0,57,57,1934.0,...,0.724,62,302,364,118,65,20,125,167,1159
4,Jaylen Brown,1627759,2020-21,00,1610612738,BOS,24.0,58,58,1999.0,...,0.764,71,276,347,195,72,32,158,168,1430
5,Jaylen Brown,1627759,2021-22,00,1610612738,BOS,25.0,66,66,2220.0,...,0.758,53,351,404,231,70,18,178,163,1559
6,Jaylen Brown,1627759,2022-23,00,1610612738,BOS,26.0,67,67,2405.0,...,0.765,78,381,459,232,75,26,197,172,1784
7,Jaylen Brown,1627759,2023-24,00,1610612738,BOS,27.0,70,70,2343.0,...,0.703,84,303,387,249,83,37,166,185,1610

In [299]:
df2 = [df,df1]

In [300]:
df2 = pd.concat([df,df1])

df2

,Player_Name,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,Jayson Tatum,1628369,2017-18,00,1610612738,BOS,20.0,80,80,2443.0,...,0.826,50,352,402,128,83,58,114,170,1112
1,Jayson Tatum,1628369,2018-19,00,1610612738,BOS,21.0,79,79,2455.0,...,0.855,70,407,477,168,84,57,122,168,1243
2,Jayson Tatum,1628369,2019-20,00,1610612738,BOS,22.0,66,66,2265.0,...,0.812,64,396,460,200,93,57,155,136,1547
3,Jayson Tatum,1628369,2020-21,00,1610612738,BOS,23.0,64,64,2290.0,...,0.868,50,422,472,276,75,31,171,122,1692
4,Jayson Tatum,1628369,2021-22,00,1610612738,BOS,24.0,76,76,2731.0,...,0.853,85,524,609,334,75,49,217,174,2046
5,Jayson Tatum,1628369,2022-23,00,1610612738,BOS,25.0,74,74,2732.0,...,0.854,78,571,649,342,78,51,213,160,2225
6,Jayson Tatum,1628369,2023-24,00,1610612738,BOS,26.0,74,74,2645.0,...,0.833,67,534,601,364,75,43,188,145,1987
0,Jaylen Brown,1627759,2016-17,00,1610612738,BOS,20.0,78,20,1341.0,...,0.685,45,175,220,64,35,18,68,142,515
1,Jaylen Brown,1627759,2017-18,00,1610612738,BOS,21.0,70,70,2152.0,...,0.644,66,280,346,114,70,26,124,181,1017
2,Jaylen Brown,1627759,2018-19,00,1610612738,BOS,22.0,74,25,1913.0,...,0.658,65,248,313,100,69,32,99,186,964
3,Jaylen Brown,1627759,2019-20,00,1610612738,BOS,23.0,57,57,1934.0,...,0.724,62,302,364,118,65,20,125,167,1159
4,Jaylen Brown,1627759,2020-21,00,1610612738,BOS,24.0,58,58,1999.0,...,0.764,71,276,347,195,72,32,158,168,1430
5,Jaylen Brown,1627759,2021-22,00,1610612738,BOS,25.0,66,66,2220.0,...,0.758,53,351,404,231,70,18,178,163,1559
6,Jaylen Brown,1627759,2022-23,00,1610612738,BOS,26.0,67,67,2405.0,...,0.765,78,381,459,232,75,26,197,172,1784
7,Jaylen Brown,1627759,2023-24,00,1610612738,BOS,27.0,70,70,2343.0,...,0.703,84,303,387,249,83,37,166,185,1610

In [301]:
scoringAllbyYear = list()
for i in range (0,9):
    scoringAllbyYear.append(scoringALL[i])
for i in range (10,13):
    for item in scoringALL[i]:
        scoringAllbyYear.append(item)
scoringAllbyYear.pop()

[2023]

In [302]:
##with open('ScoringAllByYear.pkl','wb') as f: #opens file
#    pickle.dump(scoringAllbyYear,f)

In [303]:
len(scoringAllbyYear)

39

In [304]:
namesNoYears=list()
for item in scoringAllbyYear:
    for name in item:
        if type(name) == int:
            pass
        else:
            tmpName=str(name)
            tmpName= str(name.split(',')[1])+' '+str(name.split(',')[0])
            print(tmpName)
            namesNoYears.append(tmpName)
            #for char in name:    
            #    if char.isalpha() == True or char == ' ':
            #        pass
            #    else:
            #      scoringAllbyYear.remove(name)

George Gervin
Moses Malone
Julius Erving
World B. Free
Kareem Abdul-Jabbar
Dan Issel
Adrian Dantley
Elvin Hayes
Otis Birdsong
Mike Mitchell
Adrian Dantley
Moses Malone
George Gervin
Kareem Abdul-Jabbar
Julius Erving
Mike Mitchell
David Thompson
Alex English
Jamaal Wilkes
Bernard King
George Gervin
Moses Malone
Adrian Dantley
Alex English
Julius Erving
Gus Williams
Dan Issel
Bernard King
Kareem Abdul-Jabbar
World B. Free
Alex English
Kiki Vandeweghe
George Gervin
Mark Aguirre
Reggie Theus
Moses Malone
Joe Barry Carroll
Larry Bird
Isiah Thomas
Jim Paxson
Adrian Dantley
Mark Aguirre
Kiki Vandeweghe
Alex English
Bernard King
George Gervin
Larry Bird
Terry Cummings
Mike Mitchell
Rolando Blackman
Michael Jordan
Larry Bird
Alex English
Dominique Wilkins
Purvis Short
Mark Aguirre
Moses Malone
Eddie Johnson
Terry Cummings
Mike Mitchell
Alex English
Dominique Wilkins
Adrian Dantley
Larry Bird
Kiki Vandeweghe
Mike Mitchell
Kareem Abdul-Jabbar
Jeff Malone
Rolando Blackman
Moses Malone
Michael Jordan
Alex English
Dominique Wilkins
Kiki Vandeweghe
Larry Bird
Mark Aguirre
Dale Ellis
Kevin McHale
Tom Chambers
Magic Johnson
Michael Jordan
Dominique Wilkins
Larry Bird
Karl Malone
Charles Barkley
Clyde Drexler
Alex English
Dale Ellis
Mark Aguirre
Hakeem Olajuwon
Michael Jordan
Karl Malone
Patrick Ewing
Chris Mullin
David Robinson
Dominique Wilkins
Tim Hardaway
Reggie Miller
Charles Barkley
Mitch Richmond
Michael Jordan
Karl Malone
Chris Mullin
Patrick Ewing
Clyde Drexler
Tim Hardaway
Mitch Richmond
Glen Rice
Charles Barkley
Scottie Pippen
Michael Jordan
Karl Malone
Hakeem Olajuwon
Dominique Wilkins
Patrick Ewing
Charles Barkley
David Robinson
Shaquille O'Neal
Larry Johnson
Joe Dumars
David Robinson
Shaquille O'Neal
Hakeem Olajuwon
Karl Malone
Patrick Ewing
Dominique Wilkins
Mitch Richmond
Latrell Sprewell
Glen Rice
Clifford Robinson
Shaquille O'Neal
David Robinson
Karl Malone
Hakeem Olajuwon
Jamal Mashburn
Patrick Ewing
Mitch Richmond
Glen Rice
Glenn Robinson
Scottie Pippen
Michael Jordan
Karl Malone
David Robinson
Hakeem Olajuwon
Mitch Richmond
Juwan Howard
Anfernee Hardaway
Vin Baker
Patrick Ewing
Glen Rice
Michael Jordan
Karl Malone
Glen Rice
Mitch Richmond
Latrell Sprewell
Hakeem Olajuwon
Kendall Gill
Allen Iverson
Gary Payton
Patrick Ewing
Michael Jordan
Karl Malone
Antoine Walker
Shareef Abdur-Rahim
Glen Rice
Michael Finley
Allen Iverson
Tim Duncan
Grant Hill
Shaquille O'Neal
Shaquille O'Neal
Allen Iverson
Karl Malone
Shareef Abdur-Rahim
Tim Duncan
Gary Payton
Antonio McDyess
Grant Hill
Stephon Marbury
Michael Finley
Jerry Stackhouse
Allen Iverson
Shaquille O'Neal
Paul Pierce
Vince Carter
Tracy McGrady
Antawn Jamison
Kobe Bryant
Chris Webber
Antoine Walker
Paul Pierce
Tim Duncan
Kobe Bryant
Tracy McGrady
Allen Iverson
Shaquille O'Neal
Gary Payton
Antoine Walker
Karl Malone
Dirk Nowitzki
Kobe Bryant
Tracy McGrady
Allen Iverson
Paul Pierce
Dirk Nowitzki
Tim Duncan
Kevin Garnett
Allan Houston
Shaquille O'Neal
Antawn Jamison
Kevin Garnett
Peja StojakoviÄ
Tracy McGrady
Paul Pierce
Michael Redd
Carmelo Anthony
Dirk Nowitzki
LeBron James
Vince Carter
Stephon Marbury
Allen Iverson
LeBron James
Amar'e Stoudemire
Gilbert Arenas
Dirk Nowitzki
Tracy McGrady
Vince Carter
Ray Allen
Dwyane Wade
Kobe Bryant
Kobe Bryant
LeBron James
Allen Iverson
Gilbert Arenas
Dirk Nowitzki
Carmelo Anthony
Paul Pierce
Dwyane Wade
Michael Redd
Ray Allen
Kobe Bryant
LeBron James
Gilbert Arenas
Vince Carter
Dirk Nowitzki
Carmelo Anthony
Ben Gordon
Tracy McGrady
Allen Iverson
Kevin Garnett
Kobe Bryant
LeBron James
Allen Iverson
Amar'e Stoudemire
Carmelo Anthony
Richard Jefferson
Dirk Nowitzki
Baron Davis
Jason Richardson
Joe Johnson
Dwyane Wade
LeBron James
Kobe Bryant
Dirk Nowitzki
Kevin Durant
Antawn Jamison
Chris Paul
Brandon Roy
Chris Bosh
Danny Granger
Kevin Durant
LeBron James
Kobe Bryant
Derrick Rose
Amar'e Stoudemire
Carmelo Anthony
Dwyane Wade
Monta Ellis
Kevin Martin
Blake Griffin
Kevin Durant
LeBron James
Kobe Bryant
Russell Westbrook
Kevin Love
Blake Griffin
Dirk Nowitzki
Brandon Jennings
Carmelo Anthony
Josh Smith
Kevin Durant
Kobe Bryant
LeBron James
James Harden
Carmelo Anthony
Russell Westbrook
Stephen Curry
Monta Ellis
Damian Lillard
LaMarcus Aldridge
Kevin Durant
Carmelo Anthony
LeBron James
Kevin Love
Blake Griffin
Stephen Curry
James Harden
DeMar DeRozan
Paul George
Dirk Nowitzki
James Harden
Stephen Curry
Russell Westbrook
LeBron James
Damian Lillard
Klay Thompson
LaMarcus Aldridge
Anthony Davis
Kyrie Irving
Chris Paul
James Harden
Stephen Curry
Kevin Durant
LeBron James
Damian Lillard
Russell Westbrook
Paul George
DeMar DeRozan
Isaiah Thomas
Klay Thompson
Russell Westbrook
James Harden
Isaiah Thomas
Anthony Davis
Karl-Anthony Towns
Damian Lillard
DeMar DeRozan
Stephen Curry
LeBron James
DeMarcus Cousins
LeBron James
James Harden
Anthony Davis
Russell Westbrook
Giannis Antetokounmpo
Damian Lillard
Bradley Beal
DeMar DeRozan
Kevin Durant
Lou Williams
James Harden
Paul George
Kemba Walker
Bradley Beal
Damian Lillard
Kevin Durant
Giannis Antetokounmpo
Stephen Curry
Karl-Anthony Towns
Blake Griffin
James Harden
Damian Lillard
Devin Booker
Giannis Antetokounmpo
Trae Young
Luka DonÄiÄ
Bradley Beal
LeBron James
Donovan Mitchell
Anthony Davis
Stephen Curry
Damian Lillard
Nikola JokiÄ
Bradley Beal
Luka DonÄiÄ
Giannis Antetokounmpo
Devin Booker
Julius Randle
Jayson Tatum
Zion Williamson
Trae Young
DeMar DeRozan
Joel Embiid
Jayson Tatum
Nikola JokiÄ
Giannis Antetokounmpo
Luka DonÄiÄ
Devin Booker
Karl-Anthony Towns
Donovan Mitchell

In [305]:
for item in namesNoYears:
    for char in item:    
        if char.isalpha() == True or char == ' ':
            pass
        else:
          namesNoYears.remove(item)

ValueError: list.remove(x): x not in list

In [306]:
len(namesNoYears)

366

In [307]:
namesNoYears

['George Gervin',
 'Moses Malone',
 'Julius Erving',
 'Dan Issel',
 'Adrian Dantley',
 'Elvin Hayes',
 'Otis Birdsong',
 'Mike Mitchell',
 'Adrian Dantley',
 'Moses Malone',
 'George Gervin',
 'Julius Erving',
 'Mike Mitchell',
 'David Thompson',
 'Alex English',
 'Jamaal Wilkes',
 'Bernard King',
 'George Gervin',
 'Moses Malone',
 'Adrian Dantley',
 'Alex English',
 'Julius Erving',
 'Gus Williams',
 'Dan Issel',
 'Bernard King',
 'World B. Free',
 'Alex English',
 'Kiki Vandeweghe',
 'George Gervin',
 'Mark Aguirre',
 'Reggie Theus',
 'Moses Malone',
 'Joe Barry Carroll',
 'Larry Bird',
 'Isiah Thomas',
 'Jim Paxson',
 'Adrian Dantley',
 'Mark Aguirre',
 'Kiki Vandeweghe',
 'Alex English',
 'Bernard King',
 'George Gervin',
 'Larry Bird',
 'Terry Cummings',
 'Mike Mitchell',
 'Rolando Blackman',
 'Michael Jordan',
 'Larry Bird',
 'Alex English',
 'Dominique Wilkins',
 'Purvis Short',
 'Mark Aguirre',
 'Moses Malone',
 'Eddie Johnson',
 'Terry Cummings',
 'Mike Mitchell',
 'Alex English',
 'Dominique Wilkins',
 'Adrian Dantley',
 'Larry Bird',
 'Kiki Vandeweghe',
 'Mike Mitchell',
 'Kareem Abdul-Jabbar',
 'Jeff Malone',
 'Rolando Blackman',
 'Moses Malone',
 'Michael Jordan',
 'Alex English',
 'Dominique Wilkins',
 'Kiki Vandeweghe',
 'Larry Bird',
 'Mark Aguirre',
 'Dale Ellis',
 'Kevin McHale',
 'Tom Chambers',
 'Magic Johnson',
 'Michael Jordan',
 'Dominique Wilkins',
 'Larry Bird',
 'Karl Malone',
 'Charles Barkley',
 'Clyde Drexler',
 'Alex English',
 'Dale Ellis',
 'Mark Aguirre',
 'Hakeem Olajuwon',
 'Michael Jordan',
 'Karl Malone',
 'Patrick Ewing',
 'Chris Mullin',
 'David Robinson',
 'Dominique Wilkins',
 'Tim Hardaway',
 'Reggie Miller',
 'Charles Barkley',
 'Mitch Richmond',
 'Michael Jordan',
 'Karl Malone',
 'Chris Mullin',
 'Patrick Ewing',
 'Clyde Drexler',
 'Tim Hardaway',
 'Mitch Richmond',
 'Glen Rice',
 'Charles Barkley',
 'Scottie Pippen',
 'Michael Jordan',
 'Karl Malone',
 'Hakeem Olajuwon',
 'Dominique Wilkins',
 'Patrick Ewing',
 'Charles Barkley',
 'David Robinson',
 'Larry Johnson',
 'Joe Dumars',
 'David Robinson',
 'Hakeem Olajuwon',
 'Karl Malone',
 'Patrick Ewing',
 'Dominique Wilkins',
 'Mitch Richmond',
 'Latrell Sprewell',
 'Glen Rice',
 'Clifford Robinson',
 'David Robinson',
 'Karl Malone',
 'Hakeem Olajuwon',
 'Jamal Mashburn',
 'Patrick Ewing',
 'Mitch Richmond',
 'Glen Rice',
 'Glenn Robinson',
 'Scottie Pippen',
 'Michael Jordan',
 'Karl Malone',
 'David Robinson',
 'Hakeem Olajuwon',
 'Mitch Richmond',
 'Juwan Howard',
 'Anfernee Hardaway',
 'Vin Baker',
 'Patrick Ewing',
 'Glen Rice',
 'Michael Jordan',
 'Karl Malone',
 'Glen Rice',
 'Mitch Richmond',
 'Latrell Sprewell',
 'Hakeem Olajuwon',
 'Kendall Gill',
 'Allen Iverson',
 'Gary Payton',
 'Patrick Ewing',
 'Michael Jordan',
 'Karl Malone',
 'Antoine Walker',
 'Glen Rice',
 'Michael Finley',
 'Allen Iverson',
 'Tim Duncan',
 'Grant Hill',
 'Allen Iverson',
 'Karl Malone',
 'Tim Duncan',
 'Gary Payton',
 'Antonio McDyess',
 'Grant Hill',
 'Stephon Marbury',
 'Michael Finley',
 'Jerry Stackhouse',
 'Allen Iverson',
 'Paul Pierce',
 'Vince Carter',
 'Tracy McGrady',
 'Antawn Jamison',
 'Kobe Bryant',
 'Chris Webber',
 'Antoine Walker',
 'Paul Pierce',
 'Tim Duncan',
 'Kobe Bryant',
 'Tracy McGrady',
 'Allen Iverson',
 'Gary Payton',
 'Antoine Walker',
 'Karl Malone',
 'Dirk Nowitzki',
 'Kobe Bryant',
 'Tracy McGrady',
 'Allen Iverson',
 'Paul Pierce',
 'Dirk Nowitzki',
 'Tim Duncan',
 'Kevin Garnett',
 'Allan Houston',
 "Shaquille O'Neal",
 'Antawn Jamison',
 'Kevin Garnett',
 'Tracy McGrady',
 'Paul Pierce',
 'Michael Redd',
 'Carmelo Anthony',
 'Dirk Nowitzki',
 'LeBron James',
 'Vince Carter',
 'Stephon Marbury',
 'Allen Iverson',
 'LeBron James',
 'Gilbert Arenas',
 'Dirk Nowitzki',
 'Tracy McGrady',
 'Vince Carter',
 'Ray Allen',
 'Dwyane Wade',
 'Kobe Bryant',
 'Kobe Bryant',
 'LeBron James',
 'Allen Iverson',
 'Gilbert Arenas',
 'Dirk Nowitzki',
 'Carmelo Anthony',
 'Paul Pierce',
 'Dwyane Wade',
 'Michael Redd',
 'Ray Allen',
 'Kobe Bryant',
 'LeBron James',
 'Gilbert Arenas',
 'Vince Carter',
 'Dirk Nowitzki',
 'Carmelo Anthony',
 'Ben Gordon',
 'Tracy McGrady',
 'Allen Iverson',
 'Kevin Garnett',
 'Kobe Bryant',
 'LeBron James',
 'Allen Iverson',
 'Carmelo Anthony',
 'Richard Jefferson',
 'Dirk Nowitzki',
 'Baron Davis',
 'Jason Richardson',
 'Joe Johnson',
 'Dwyane Wade',
 'LeBron James',
 'Kobe Bryant',
 'Dirk Nowitzki',
 'Kevin Durant',
 'Antawn Jamison',
 'Chris Paul',
 'Brandon Roy',
 'Chris Bosh',
 'Danny Granger',
 'Kevin Durant',
 'LeBron James',
 'Kobe Bryant',
 'Derrick Rose',
 'Carmelo Anthony',
 'Dwyane Wade',
 'Monta Ellis',
 'Kevin Martin',
 'Blake Griffin',
 'Kevin Durant',
 'LeBron James',
 'Kobe Bryant',
 'Russell Westbrook',
 'Kevin Love',
 'Blake Griffin',
 'Dirk Nowitzki',
 'Brandon Jennings',
 'Carmelo Anthony',
 'Josh Smith',
 'Kevin Durant',
 'Kobe Bryant',
 'LeBron James',
 'James Harden',
 'Carmelo Anthony',
 'Russell Westbrook',
 'Stephen Curry',
 'Monta Ellis',
 'Damian Lillard',
 'LaMarcus Aldridge',
 'Kevin Durant',
 'Carmelo Anthony',
 'LeBron James',
 'Kevin Love',
 'Blake Griffin',
 'Stephen Curry',
 'James Harden',
 'DeMar DeRozan',
 'Paul George',
 'Dirk Nowitzki',
 'James Harden',
 'Stephen Curry',
 'Russell Westbrook',
 'LeBron James',
 'Damian Lillard',
 'Klay Thompson',
 'LaMarcus Aldridge',
 'Anthony Davis',
 'Kyrie Irving',
 'Chris Paul',
 'James Harden',
 'Stephen Curry',
 'Kevin Durant',
 'LeBron James',
 'Damian Lillard',
 'Russell Westbrook',
 'Paul George',
 'DeMar DeRozan',
 'Isaiah Thomas',
 'Klay Thompson',
 'Russell Westbrook',
 'James Harden',
 'Isaiah Thomas',
 'Anthony Davis',
 'Damian Lillard',
 'DeMar DeRozan',
 'Stephen Curry',
 'LeBron James',
 'DeMarcus Cousins',
 'LeBron James',
 'James Harden',
 'Anthony Davis',
 'Russell Westbrook',
 'Giannis Antetokounmpo',
 'Damian Lillard',
 'Bradley Beal',
 'DeMar DeRozan',
 'Kevin Durant',
 'Lou Williams',
 'James Harden',
 'Paul George',
 'Kemba Walker',
 'Bradley Beal',
 'Damian Lillard',
 'Kevin Durant',
 'Giannis Antetokounmpo',
 'Stephen Curry',
 'Blake Griffin',
 'James Harden',
 'Damian Lillard',
 'Devin Booker',
 'Giannis Antetokounmpo',
 'Trae Young',
 'Bradley Beal',
 'LeBron James',
 'Donovan Mitchell',
 'Anthony Davis',
 'Stephen Curry',
 'Damian Lillard',
 'Bradley Beal',
 'Giannis Antetokounmpo',
 'Devin Booker',
 'Julius Randle',
 'Jayson Tatum',
 'Zion Williamson',
 'Trae Young',
 'DeMar DeRozan',
 'Joel Embiid',
 'Jayson Tatum',
 'Giannis Antetokounmpo',
 'Devin Booker',
 'Karl-Anthony Towns',
 'Donovan Mitchell']

In [308]:
NamesLystClean = namesNoYears

In [312]:
with open('scoringAllbyYearClean.pkl', 'rb') as f:
    scoringAllbyYearClean = pickle.load(f) # deserialize using load()

In [313]:
scoringAllbyYearClean

[['George Gervin',
  'Moses Malone',
  'Julius Erving',
  'Kareem Abdul-Jabbar',
  'Dan Issel',
  'Adrian Dantley',
  'Elvin Hayes',
  'Otis Birdsong',
  'Mike Mitchell',
  1980],
 ['Adrian Dantley',
  'Moses Malone',
  'George Gervin',
  'Julius Erving',
  'Mike Mitchell',
  'David Thompson',
  'Alex English',
  'Jamaal Wilkes',
  'Bernard King',
  1981],
 ['George Gervin',
  'Moses Malone',
  'Adrian Dantley',
  'Alex English',
  'Julius Erving',
  'Gus Williams',
  'Dan Issel',
  'Bernard King',
  'World B. Free',
  1982],
 ['Alex English',
  'Kiki Vandeweghe',
  'George Gervin',
  'Mark Aguirre',
  'Reggie Theus',
  'Moses Malone',
  'Joe Barry Carroll',
  'Larry Bird',
  'Isiah Thomas',
  'Jim Paxson',
  1983],
 ['Adrian Dantley',
  'Mark Aguirre',
  'Kiki Vandeweghe',
  'Alex English',
  'Bernard King',
  'George Gervin',
  'Larry Bird',
  'Terry Cummings',
  'Mike Mitchell',
  'Rolando Blackman',
  1984],
 ['Michael Jordan',
  'Larry Bird',
  'Alex English',
  'Dominique Wilkins',
  'Purvis Short',
  'Mark Aguirre',
  'Moses Malone',
  'Eddie Johnson',
  'Terry Cummings',
  'Mike Mitchell',
  1985],
 ['Alex English',
  'Dominique Wilkins',
  'Adrian Dantley',
  'Larry Bird',
  'Kiki Vandeweghe',
  'Mike Mitchell',
  'Jeff Malone',
  'Rolando Blackman',
  'Moses Malone',
  1986],
 ['Michael Jordan',
  'Alex English',
  'Dominique Wilkins',
  'Kiki Vandeweghe',
  'Larry Bird',
  'Mark Aguirre',
  'Dale Ellis',
  'Kevin McHale',
  'Tom Chambers',
  'Magic Johnson',
  1987],
 ['Michael Jordan',
  'Dominique Wilkins',
  'Larry Bird',
  'Karl Malone',
  'Charles Barkley',
  'Clyde Drexler',
  'Alex English',
  'Dale Ellis',
  'Mark Aguirre',
  'Hakeem Olajuwon',
  1988],
 ['Michael Jordan',
  'Karl Malone',
  'Patrick Ewing',
  'Chris Mullin',
  'David Robinson',
  'Dominique Wilkins',
  'Tim Hardaway',
  'Reggie Miller',
  'Charles Barkley',
  'Mitch Richmond',
  1991],
 ['Michael Jordan',
  'Karl Malone',
  'Chris Mullin',
  'Patrick Ewing',
  'Clyde Drexler',
  'Tim Hardaway',
  'Mitch Richmond',
  'Glen Rice',
  'Charles Barkley',
  'Scottie Pippen',
  1992],
 ['Michael Jordan',
  'Karl Malone',
  'Hakeem Olajuwon',
  'Dominique Wilkins',
  'Patrick Ewing',
  'Charles Barkley',
  'David Robinson',
  'Larry Johnson',
  'Joe Dumars',
  1993],
 ['David Robinson',
  'Hakeem Olajuwon',
  'Karl Malone',
  'Patrick Ewing',
  'Dominique Wilkins',
  'Mitch Richmond',
  'Latrell Sprewell',
  'Glen Rice',
  'Clifford Robinson',
  1994],
 ['David Robinson',
  'Karl Malone',
  'Hakeem Olajuwon',
  'Jamal Mashburn',
  'Patrick Ewing',
  'Mitch Richmond',
  'Glen Rice',
  'Glenn Robinson',
  'Scottie Pippen',
  1995],
 ['Michael Jordan',
  'Karl Malone',
  'David Robinson',
  'Hakeem Olajuwon',
  'Mitch Richmond',
  'Juwan Howard',
  'Anfernee Hardaway',
  'Vin Baker',
  'Patrick Ewing',
  'Glen Rice',
  1996],
 ['Michael Jordan',
  'Karl Malone',
  'Glen Rice',
  'Mitch Richmond',
  'Latrell Sprewell',
  'Hakeem Olajuwon',
  'Kendall Gill',
  'Allen Iverson',
  'Gary Payton',
  'Patrick Ewing',
  1997],
 ['Michael Jordan',
  'Karl Malone',
  'Antoine Walker',
  'Glen Rice',
  'Michael Finley',
  'Allen Iverson',
  'Tim Duncan',
  'Grant Hill',
  1998],
 ['Allen Iverson',
  'Karl Malone',
  'Tim Duncan',
  'Gary Payton',
  'Antonio McDyess',
  'Grant Hill',
  'Stephon Marbury',
  'Michael Finley',
  1999],
 ['Jerry Stackhouse',
  'Allen Iverson',
  'Paul Pierce',
  'Vince Carter',
  'Tracy McGrady',
  'Antawn Jamison',
  'Kobe Bryant',
  'Chris Webber',
  'Antoine Walker',
  2001],
 ['Paul Pierce',
  'Tim Duncan',
  'Kobe Bryant',
  'Tracy McGrady',
  'Allen Iverson',
  'Gary Payton',
  'Antoine Walker',
  'Karl Malone',
  'Dirk Nowitzki',
  2002],
 ['Kobe Bryant',
  'Tracy McGrady',
  'Allen Iverson',
  'Paul Pierce',
  'Dirk Nowitzki',
  'Tim Duncan',
  'Kevin Garnett',
  'Allan Houston',
  'Antawn Jamison',
  2003],
 ['Kevin Garnett',
  'Tracy McGrady',
  'Paul Pierce',
  'Michael Redd',
  'Carmelo Anthony',
  'Dirk Nowitzki',
  'LeBron James',
  'Vince Carter',
  'Stephon Marbury',
  2004],
 ['Allen Iverson',
  'LeBron James',
  'Gilbert Arenas',
  'Dirk Nowitzki',
  'Tracy McGrady',
  'Vince Carter',
  'Ray Allen',
  'Dwyane Wade',
  'Kobe Bryant',
  2005],
 ['Kobe Bryant',
  'LeBron James',
  'Allen Iverson',
  'Gilbert Arenas',
  'Dirk Nowitzki',
  'Carmelo Anthony',
  'Paul Pierce',
  'Dwyane Wade',
  'Michael Redd',
  'Ray Allen',
  2006],
 ['Kobe Bryant',
  'LeBron James',
  'Gilbert Arenas',
  'Vince Carter',
  'Dirk Nowitzki',
  'Carmelo Anthony',
  'Ben Gordon',
  'Tracy McGrady',
  'Allen Iverson',
  'Kevin Garnett',
  2007],
 ['Kobe Bryant',
  'LeBron James',
  'Allen Iverson',
  'Carmelo Anthony',
  'Richard Jefferson',
  'Dirk Nowitzki',
  'Baron Davis',
  'Jason Richardson',
  'Joe Johnson',
  2008],
 ['Dwyane Wade',
  'LeBron James',
  'Kobe Bryant',
  'Dirk Nowitzki',
  'Kevin Durant',
  'Antawn Jamison',
  'Chris Paul',
  'Brandon Roy',
  'Chris Bosh',
  'Danny Granger',
  2009],
 ['Kevin Durant',
  'LeBron James',
  'Kobe Bryant',
  'Derrick Rose',
  'Carmelo Anthony',
  'Dwyane Wade',
  'Monta Ellis',
  'Kevin Martin',
  'Blake Griffin',
  2011],
 ['Kevin Durant',
  'LeBron James',
  'Kobe Bryant',
  'Russell Westbrook',
  'Kevin Love',
  'Blake Griffin',
  'Dirk Nowitzki',
  'Brandon Jennings',
  'Carmelo Anthony',
  'Josh Smith',
  2012],
 ['Kevin Durant',
  'Kobe Bryant',
  'LeBron James',
  'James Harden',
  'Carmelo Anthony',
  'Russell Westbrook',
  'Stephen Curry',
  'Monta Ellis',
  'Damian Lillard',
  'LaMarcus Aldridge',
  2013],
 ['Kevin Durant',
  'Carmelo Anthony',
  'LeBron James',
  'Kevin Love',
  'Blake Griffin',
  'Stephen Curry',
  'James Harden',
  'DeMar DeRozan',
  'Paul George',
  'Dirk Nowitzki',
  2014],
 ['James Harden',
  'Stephen Curry',
  'Russell Westbrook',
  'LeBron James',
  'Damian Lillard',
  'Klay Thompson',
  'LaMarcus Aldridge',
  'Anthony Davis',
  'Kyrie Irving',
  'Chris Paul',
  2015],
 ['James Harden',
  'Stephen Curry',
  'Kevin Durant',
  'LeBron James',
  'Damian Lillard',
  'Russell Westbrook',
  'Paul George',
  'DeMar DeRozan',
  'Isaiah Thomas',
  'Klay Thompson',
  2016],
 ['Russell Westbrook',
  'James Harden',
  'Isaiah Thomas',
  'Anthony Davis',
  'Damian Lillard',
  'DeMar DeRozan',
  'Stephen Curry',
  'LeBron James',
  'DeMarcus Cousins',
  2017],
 ['LeBron James',
  'James Harden',
  'Anthony Davis',
  'Russell Westbrook',
  'Giannis Antetokounmpo',
  'Damian Lillard',
  'Bradley Beal',
  'DeMar DeRozan',
  'Kevin Durant',
  'Lou Williams',
  2018],
 ['James Harden',
  'Paul George',
  'Kemba Walker',
  'Bradley Beal',
  'Damian Lillard',
  'Kevin Durant',
  'Giannis Antetokounmpo',
  'Stephen Curry',
  'Blake Griffin',
  2019],
 ['James Harden',
  'Damian Lillard',
  'Devin Booker',
  'Giannis Antetokounmpo',
  'Trae Young',
  'Bradley Beal',
  'LeBron James',
  'Donovan Mitchell',
  'Anthony Davis',
  2020],
 ['Stephen Curry',
  'Damian Lillard',
  'Bradley Beal',
  'Giannis Antetokounmpo',
  'Devin Booker',
  'Julius Randle',
  'Jayson Tatum',
  'Zion Williamson',
  2021],
 ['Trae Young',
  'DeMar DeRozan',
  'Joel Embiid',
  'Jayson Tatum',
  'Giannis Antetokounmpo',
  'Devin Booker',
  'Donovan Mitchell',
  2022]]

In [311]:
#with open('NamesLystClean.pkl','wb') as f: #opens file
 #  pickle.dump(NamesLystClean,f)

In [341]:
mainDF = df

In [342]:
mainDF.drop([0,1,2,3,4,5,6])

Empty DataFrame
Columns: [Player_Name, PLAYER_ID, SEASON_ID, LEAGUE_ID, TEAM_ID, TEAM_ABBREVIATION, PLAYER_AGE, GP, GS, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TOV, PF, PTS]
Index: []

[0 rows x 28 columns]

In [ ]:
df

,Player_Name,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,Jayson Tatum,1628369,2017-18,00,1610612738,BOS,20.0,80,80,2443.0,...,0.826,50,352,402,128,83,58,114,170,1112
1,Jayson Tatum,1628369,2018-19,00,1610612738,BOS,21.0,79,79,2455.0,...,0.855,70,407,477,168,84,57,122,168,1243
2,Jayson Tatum,1628369,2019-20,00,1610612738,BOS,22.0,66,66,2265.0,...,0.812,64,396,460,200,93,57,155,136,1547
3,Jayson Tatum,1628369,2020-21,00,1610612738,BOS,23.0,64,64,2290.0,...,0.868,50,422,472,276,75,31,171,122,1692
4,Jayson Tatum,1628369,2021-22,00,1610612738,BOS,24.0,76,76,2731.0,...,0.853,85,524,609,334,75,49,217,174,2046
5,Jayson Tatum,1628369,2022-23,00,1610612738,BOS,25.0,74,74,2732.0,...,0.854,78,571,649,342,78,51,213,160,2225
6,Jayson Tatum,1628369,2023-24,00,1610612738,BOS,26.0,74,74,2645.0,...,0.833,67,534,601,364,75,43,188,145,1987

In [345]:
mainDF=df
mainDF= mainDF.drop([0,1,2,3,4,5,6])
mainDF

Empty DataFrame
Columns: [Player_Name, PLAYER_ID, SEASON_ID, LEAGUE_ID, TEAM_ID, TEAM_ABBREVIATION, PLAYER_AGE, GP, GS, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TOV, PF, PTS]
Index: []

[0 rows x 28 columns]

In [343]:
mainDF

,Player_Name,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,Jayson Tatum,1628369,2017-18,00,1610612738,BOS,20.0,80,80,2443.0,...,0.826,50,352,402,128,83,58,114,170,1112
1,Jayson Tatum,1628369,2018-19,00,1610612738,BOS,21.0,79,79,2455.0,...,0.855,70,407,477,168,84,57,122,168,1243
2,Jayson Tatum,1628369,2019-20,00,1610612738,BOS,22.0,66,66,2265.0,...,0.812,64,396,460,200,93,57,155,136,1547
3,Jayson Tatum,1628369,2020-21,00,1610612738,BOS,23.0,64,64,2290.0,...,0.868,50,422,472,276,75,31,171,122,1692
4,Jayson Tatum,1628369,2021-22,00,1610612738,BOS,24.0,76,76,2731.0,...,0.853,85,524,609,334,75,49,217,174,2046
5,Jayson Tatum,1628369,2022-23,00,1610612738,BOS,25.0,74,74,2732.0,...,0.854,78,571,649,342,78,51,213,160,2225
6,Jayson Tatum,1628369,2023-24,00,1610612738,BOS,26.0,74,74,2645.0,...,0.833,67,534,601,364,75,43,188,145,1987

In [ ]:
scoringAllbyYearClean = scoringAllbyYear

In [ ]:

for year in scoringAllbyYearClean:
    for name in year:
        if type(name) == int:
            pass
        else:
            tmpName=str(name)
            tmpName= str(name.split(',')[1])+' '+str(name.split(',')[0])
            year[name] = tmpName

TypeError: list indices must be integers or slices, not str

In [ ]:

for year in scoringAllbyYearClean:
    for i in range(len(year)):
        if type(year[i]) == int:
            pass
        else:
            tmpName=str(year[i])
            tmpName= str(year[i].split(',')[1])+' '+str(year[i].split(',')[0])
            year[i] = tmpName

In [ ]:
scoringAllbyYearClean

[['George Gervin',
  'Moses Malone',
  'Julius Erving',
  'World B. Free',
  'Kareem Abdul-Jabbar',
  'Dan Issel',
  'Adrian Dantley',
  'Elvin Hayes',
  'Otis Birdsong',
  'Mike Mitchell',
  1980],
 ['Adrian Dantley',
  'Moses Malone',
  'George Gervin',
  'Kareem Abdul-Jabbar',
  'Julius Erving',
  'Mike Mitchell',
  'David Thompson',
  'Alex English',
  'Jamaal Wilkes',
  'Bernard King',
  1981],
 ['George Gervin',
  'Moses Malone',
  'Adrian Dantley',
  'Alex English',
  'Julius Erving',
  'Gus Williams',
  'Dan Issel',
  'Bernard King',
  'Kareem Abdul-Jabbar',
  'World B. Free',
  1982],
 ['Alex English',
  'Kiki Vandeweghe',
  'George Gervin',
  'Mark Aguirre',
  'Reggie Theus',
  'Moses Malone',
  'Joe Barry Carroll',
  'Larry Bird',
  'Isiah Thomas',
  'Jim Paxson',
  1983],
 ['Adrian Dantley',
  'Mark Aguirre',
  'Kiki Vandeweghe',
  'Alex English',
  'Bernard King',
  'George Gervin',
  'Larry Bird',
  'Terry Cummings',
  'Mike Mitchell',
  'Rolando Blackman',
  1984],
 ['Michael Jordan',
  'Larry Bird',
  'Alex English',
  'Dominique Wilkins',
  'Purvis Short',
  'Mark Aguirre',
  'Moses Malone',
  'Eddie Johnson',
  'Terry Cummings',
  'Mike Mitchell',
  1985],
 ['Alex English',
  'Dominique Wilkins',
  'Adrian Dantley',
  'Larry Bird',
  'Kiki Vandeweghe',
  'Mike Mitchell',
  'Kareem Abdul-Jabbar',
  'Jeff Malone',
  'Rolando Blackman',
  'Moses Malone',
  1986],
 ['Michael Jordan',
  'Alex English',
  'Dominique Wilkins',
  'Kiki Vandeweghe',
  'Larry Bird',
  'Mark Aguirre',
  'Dale Ellis',
  'Kevin McHale',
  'Tom Chambers',
  'Magic Johnson',
  1987],
 ['Michael Jordan',
  'Dominique Wilkins',
  'Larry Bird',
  'Karl Malone',
  'Charles Barkley',
  'Clyde Drexler',
  'Alex English',
  'Dale Ellis',
  'Mark Aguirre',
  'Hakeem Olajuwon',
  1988],
 ['Michael Jordan',
  'Karl Malone',
  'Patrick Ewing',
  'Chris Mullin',
  'David Robinson',
  'Dominique Wilkins',
  'Tim Hardaway',
  'Reggie Miller',
  'Charles Barkley',
  'Mitch Richmond',
  1991],
 ['Michael Jordan',
  'Karl Malone',
  'Chris Mullin',
  'Patrick Ewing',
  'Clyde Drexler',
  'Tim Hardaway',
  'Mitch Richmond',
  'Glen Rice',
  'Charles Barkley',
  'Scottie Pippen',
  1992],
 ['Michael Jordan',
  'Karl Malone',
  'Hakeem Olajuwon',
  'Dominique Wilkins',
  'Patrick Ewing',
  'Charles Barkley',
  'David Robinson',
  "Shaquille O'Neal",
  'Larry Johnson',
  'Joe Dumars',
  1993],
 ['David Robinson',
  "Shaquille O'Neal",
  'Hakeem Olajuwon',
  'Karl Malone',
  'Patrick Ewing',
  'Dominique Wilkins',
  'Mitch Richmond',
  'Latrell Sprewell',
  'Glen Rice',
  'Clifford Robinson',
  1994],
 ["Shaquille O'Neal",
  'David Robinson',
  'Karl Malone',
  'Hakeem Olajuwon',
  'Jamal Mashburn',
  'Patrick Ewing',
  'Mitch Richmond',
  'Glen Rice',
  'Glenn Robinson',
  'Scottie Pippen',
  1995],
 ['Michael Jordan',
  'Karl Malone',
  'David Robinson',
  'Hakeem Olajuwon',
  'Mitch Richmond',
  'Juwan Howard',
  'Anfernee Hardaway',
  'Vin Baker',
  'Patrick Ewing',
  'Glen Rice',
  1996],
 ['Michael Jordan',
  'Karl Malone',
  'Glen Rice',
  'Mitch Richmond',
  'Latrell Sprewell',
  'Hakeem Olajuwon',
  'Kendall Gill',
  'Allen Iverson',
  'Gary Payton',
  'Patrick Ewing',
  1997],
 ['Michael Jordan',
  'Karl Malone',
  'Antoine Walker',
  'Shareef Abdur-Rahim',
  'Glen Rice',
  'Michael Finley',
  'Allen Iverson',
  'Tim Duncan',
  'Grant Hill',
  "Shaquille O'Neal",
  1998],
 ["Shaquille O'Neal",
  'Allen Iverson',
  'Karl Malone',
  'Shareef Abdur-Rahim',
  'Tim Duncan',
  'Gary Payton',
  'Antonio McDyess',
  'Grant Hill',
  'Stephon Marbury',
  'Michael Finley',
  1999],
 ['Jerry Stackhouse',
  'Allen Iverson',
  "Shaquille O'Neal",
  'Paul Pierce',
  'Vince Carter',
  'Tracy McGrady',
  'Antawn Jamison',
  'Kobe Bryant',
  'Chris Webber',
  'Antoine Walker',
  2001],
 ['Paul Pierce',
  'Tim Duncan',
  'Kobe Bryant',
  'Tracy McGrady',
  'Allen Iverson',
  "Shaquille O'Neal",
  'Gary Payton',
  'Antoine Walker',
  'Karl Malone',
  'Dirk Nowitzki',
  2002],
 ['Kobe Bryant',
  'Tracy McGrady',
  'Allen Iverson',
  'Paul Pierce',
  'Dirk Nowitzki',
  'Tim Duncan',
  'Kevin Garnett',
  'Allan Houston',
  "Shaquille O'Neal",
  'Antawn Jamison',
  2003],
 ['Kevin Garnett',
  'Peja StojakoviÄ\x87',
  'Tracy McGrady',
  'Paul Pierce',
  'Michael Redd',
  'Carmelo Anthony',
  'Dirk Nowitzki',
  'LeBron James',
  'Vince Carter',
  'Stephon Marbury',
  2004],
 ['Allen Iverson',
  'LeBron James',
  "Amar'e Stoudemire",
  'Gilbert Arenas',
  'Dirk Nowitzki',
  'Tracy McGrady',
  'Vince Carter',
  'Ray Allen',
  'Dwyane Wade',
  'Kobe Bryant',
  2005],
 ['Kobe Bryant',
  'LeBron James',
  'Allen Iverson',
  'Gilbert Arenas',
  'Dirk Nowitzki',
  'Carmelo Anthony',
  'Paul Pierce',
  'Dwyane Wade',
  'Michael Redd',
  'Ray Allen',
  2006],
 ['Kobe Bryant',
  'LeBron James',
  'Gilbert Arenas',
  'Vince Carter',
  'Dirk Nowitzki',
  'Carmelo Anthony',
  'Ben Gordon',
  'Tracy McGrady',
  'Allen Iverson',
  'Kevin Garnett',
  2007],
 ['Kobe Bryant',
  'LeBron James',
  'Allen Iverson',
  "Amar'e Stoudemire",
  'Carmelo Anthony',
  'Richard Jefferson',
  'Dirk Nowitzki',
  'Baron Davis',
  'Jason Richardson',
  'Joe Johnson',
  2008],
 ['Dwyane Wade',
  'LeBron James',
  'Kobe Bryant',
  'Dirk Nowitzki',
  'Kevin Durant',
  'Antawn Jamison',
  'Chris Paul',
  'Brandon Roy',
  'Chris Bosh',
  'Danny Granger',
  2009],
 ['Kevin Durant',
  'LeBron James',
  'Kobe Bryant',
  'Derrick Rose',
  "Amar'e Stoudemire",
  'Carmelo Anthony',
  'Dwyane Wade',
  'Monta Ellis',
  'Kevin Martin',
  'Blake Griffin',
  2011],
 ['Kevin Durant',
  'LeBron James',
  'Kobe Bryant',
  'Russell Westbrook',
  'Kevin Love',
  'Blake Griffin',
  'Dirk Nowitzki',
  'Brandon Jennings',
  'Carmelo Anthony',
  'Josh Smith',
  2012],
 ['Kevin Durant',
  'Kobe Bryant',
  'LeBron James',
  'James Harden',
  'Carmelo Anthony',
  'Russell Westbrook',
  'Stephen Curry',
  'Monta Ellis',
  'Damian Lillard',
  'LaMarcus Aldridge',
  2013],
 ['Kevin Durant',
  'Carmelo Anthony',
  'LeBron James',
  'Kevin Love',
  'Blake Griffin',
  'Stephen Curry',
  'James Harden',
  'DeMar DeRozan',
  'Paul George',
  'Dirk Nowitzki',
  2014],
 ['James Harden',
  'Stephen Curry',
  'Russell Westbrook',
  'LeBron James',
  'Damian Lillard',
  'Klay Thompson',
  'LaMarcus Aldridge',
  'Anthony Davis',
  'Kyrie Irving',
  'Chris Paul',
  2015],
 ['James Harden',
  'Stephen Curry',
  'Kevin Durant',
  'LeBron James',
  'Damian Lillard',
  'Russell Westbrook',
  'Paul George',
  'DeMar DeRozan',
  'Isaiah Thomas',
  'Klay Thompson',
  2016],
 ['Russell Westbrook',
  'James Harden',
  'Isaiah Thomas',
  'Anthony Davis',
  'Karl-Anthony Towns',
  'Damian Lillard',
  'DeMar DeRozan',
  'Stephen Curry',
  'LeBron James',
  'DeMarcus Cousins',
  2017],
 ['LeBron James',
  'James Harden',
  'Anthony Davis',
  'Russell Westbrook',
  'Giannis Antetokounmpo',
  'Damian Lillard',
  'Bradley Beal',
  'DeMar DeRozan',
  'Kevin Durant',
  'Lou Williams',
  2018],
 ['James Harden',
  'Paul George',
  'Kemba Walker',
  'Bradley Beal',
  'Damian Lillard',
  'Kevin Durant',
  'Giannis Antetokounmpo',
  'Stephen Curry',
  'Karl-Anthony Towns',
  'Blake Griffin',
  2019],
 ['James Harden',
  'Damian Lillard',
  'Devin Booker',
  'Giannis Antetokounmpo',
  'Trae Young',
  'Luka DonÄ\x8diÄ\x87',
  'Bradley Beal',
  'LeBron James',
  'Donovan Mitchell',
  'Anthony Davis',
  2020],
 ['Stephen Curry',
  'Damian Lillard',
  'Nikola JokiÄ\x87',
  'Bradley Beal',
  'Luka DonÄ\x8diÄ\x87',
  'Giannis Antetokounmpo',
  'Devin Booker',
  'Julius Randle',
  'Jayson Tatum',
  'Zion Williamson',
  2021],
 ['Trae Young',
  'DeMar DeRozan',
  'Joel Embiid',
  'Jayson Tatum',
  'Nikola JokiÄ\x87',
  'Giannis Antetokounmpo',
  'Luka DonÄ\x8diÄ\x87',
  'Devin Booker',
  'Karl-Anthony Towns',
  'Donovan Mitchell',
  2022]]

In [ ]:
#with open('ScoringAllByYearClean.pkl','wb') as f: #opens file
 #   pickle.dump(scoringAllbyYearClean,f)

In [ ]:
for year in scoringAllbyYearClean:
    for name in year:
        if type(name)== int:
            pass
        else:
            if name not in NamesLystClean:
                year.remove(name)

In [ ]:
scoringAllbyYearClean

[['George Gervin',
  'Moses Malone',
  'Julius Erving',
  'Kareem Abdul-Jabbar',
  'Dan Issel',
  'Adrian Dantley',
  'Elvin Hayes',
  'Otis Birdsong',
  'Mike Mitchell',
  1980],
 ['Adrian Dantley',
  'Moses Malone',
  'George Gervin',
  'Julius Erving',
  'Mike Mitchell',
  'David Thompson',
  'Alex English',
  'Jamaal Wilkes',
  'Bernard King',
  1981],
 ['George Gervin',
  'Moses Malone',
  'Adrian Dantley',
  'Alex English',
  'Julius Erving',
  'Gus Williams',
  'Dan Issel',
  'Bernard King',
  'World B. Free',
  1982],
 ['Alex English',
  'Kiki Vandeweghe',
  'George Gervin',
  'Mark Aguirre',
  'Reggie Theus',
  'Moses Malone',
  'Joe Barry Carroll',
  'Larry Bird',
  'Isiah Thomas',
  'Jim Paxson',
  1983],
 ['Adrian Dantley',
  'Mark Aguirre',
  'Kiki Vandeweghe',
  'Alex English',
  'Bernard King',
  'George Gervin',
  'Larry Bird',
  'Terry Cummings',
  'Mike Mitchell',
  'Rolando Blackman',
  1984],
 ['Michael Jordan',
  'Larry Bird',
  'Alex English',
  'Dominique Wilkins',
  'Purvis Short',
  'Mark Aguirre',
  'Moses Malone',
  'Eddie Johnson',
  'Terry Cummings',
  'Mike Mitchell',
  1985],
 ['Alex English',
  'Dominique Wilkins',
  'Adrian Dantley',
  'Larry Bird',
  'Kiki Vandeweghe',
  'Mike Mitchell',
  'Jeff Malone',
  'Rolando Blackman',
  'Moses Malone',
  1986],
 ['Michael Jordan',
  'Alex English',
  'Dominique Wilkins',
  'Kiki Vandeweghe',
  'Larry Bird',
  'Mark Aguirre',
  'Dale Ellis',
  'Kevin McHale',
  'Tom Chambers',
  'Magic Johnson',
  1987],
 ['Michael Jordan',
  'Dominique Wilkins',
  'Larry Bird',
  'Karl Malone',
  'Charles Barkley',
  'Clyde Drexler',
  'Alex English',
  'Dale Ellis',
  'Mark Aguirre',
  'Hakeem Olajuwon',
  1988],
 ['Michael Jordan',
  'Karl Malone',
  'Patrick Ewing',
  'Chris Mullin',
  'David Robinson',
  'Dominique Wilkins',
  'Tim Hardaway',
  'Reggie Miller',
  'Charles Barkley',
  'Mitch Richmond',
  1991],
 ['Michael Jordan',
  'Karl Malone',
  'Chris Mullin',
  'Patrick Ewing',
  'Clyde Drexler',
  'Tim Hardaway',
  'Mitch Richmond',
  'Glen Rice',
  'Charles Barkley',
  'Scottie Pippen',
  1992],
 ['Michael Jordan',
  'Karl Malone',
  'Hakeem Olajuwon',
  'Dominique Wilkins',
  'Patrick Ewing',
  'Charles Barkley',
  'David Robinson',
  'Larry Johnson',
  'Joe Dumars',
  1993],
 ['David Robinson',
  'Hakeem Olajuwon',
  'Karl Malone',
  'Patrick Ewing',
  'Dominique Wilkins',
  'Mitch Richmond',
  'Latrell Sprewell',
  'Glen Rice',
  'Clifford Robinson',
  1994],
 ['David Robinson',
  'Karl Malone',
  'Hakeem Olajuwon',
  'Jamal Mashburn',
  'Patrick Ewing',
  'Mitch Richmond',
  'Glen Rice',
  'Glenn Robinson',
  'Scottie Pippen',
  1995],
 ['Michael Jordan',
  'Karl Malone',
  'David Robinson',
  'Hakeem Olajuwon',
  'Mitch Richmond',
  'Juwan Howard',
  'Anfernee Hardaway',
  'Vin Baker',
  'Patrick Ewing',
  'Glen Rice',
  1996],
 ['Michael Jordan',
  'Karl Malone',
  'Glen Rice',
  'Mitch Richmond',
  'Latrell Sprewell',
  'Hakeem Olajuwon',
  'Kendall Gill',
  'Allen Iverson',
  'Gary Payton',
  'Patrick Ewing',
  1997],
 ['Michael Jordan',
  'Karl Malone',
  'Antoine Walker',
  'Glen Rice',
  'Michael Finley',
  'Allen Iverson',
  'Tim Duncan',
  'Grant Hill',
  1998],
 ['Allen Iverson',
  'Karl Malone',
  'Tim Duncan',
  'Gary Payton',
  'Antonio McDyess',
  'Grant Hill',
  'Stephon Marbury',
  'Michael Finley',
  1999],
 ['Jerry Stackhouse',
  'Allen Iverson',
  'Paul Pierce',
  'Vince Carter',
  'Tracy McGrady',
  'Antawn Jamison',
  'Kobe Bryant',
  'Chris Webber',
  'Antoine Walker',
  2001],
 ['Paul Pierce',
  'Tim Duncan',
  'Kobe Bryant',
  'Tracy McGrady',
  'Allen Iverson',
  'Gary Payton',
  'Antoine Walker',
  'Karl Malone',
  'Dirk Nowitzki',
  2002],
 ['Kobe Bryant',
  'Tracy McGrady',
  'Allen Iverson',
  'Paul Pierce',
  'Dirk Nowitzki',
  'Tim Duncan',
  'Kevin Garnett',
  'Allan Houston',
  'Antawn Jamison',
  2003],
 ['Kevin Garnett',
  'Tracy McGrady',
  'Paul Pierce',
  'Michael Redd',
  'Carmelo Anthony',
  'Dirk Nowitzki',
  'LeBron James',
  'Vince Carter',
  'Stephon Marbury',
  2004],
 ['Allen Iverson',
  'LeBron James',
  'Gilbert Arenas',
  'Dirk Nowitzki',
  'Tracy McGrady',
  'Vince Carter',
  'Ray Allen',
  'Dwyane Wade',
  'Kobe Bryant',
  2005],
 ['Kobe Bryant',
  'LeBron James',
  'Allen Iverson',
  'Gilbert Arenas',
  'Dirk Nowitzki',
  'Carmelo Anthony',
  'Paul Pierce',
  'Dwyane Wade',
  'Michael Redd',
  'Ray Allen',
  2006],
 ['Kobe Bryant',
  'LeBron James',
  'Gilbert Arenas',
  'Vince Carter',
  'Dirk Nowitzki',
  'Carmelo Anthony',
  'Ben Gordon',
  'Tracy McGrady',
  'Allen Iverson',
  'Kevin Garnett',
  2007],
 ['Kobe Bryant',
  'LeBron James',
  'Allen Iverson',
  'Carmelo Anthony',
  'Richard Jefferson',
  'Dirk Nowitzki',
  'Baron Davis',
  'Jason Richardson',
  'Joe Johnson',
  2008],
 ['Dwyane Wade',
  'LeBron James',
  'Kobe Bryant',
  'Dirk Nowitzki',
  'Kevin Durant',
  'Antawn Jamison',
  'Chris Paul',
  'Brandon Roy',
  'Chris Bosh',
  'Danny Granger',
  2009],
 ['Kevin Durant',
  'LeBron James',
  'Kobe Bryant',
  'Derrick Rose',
  'Carmelo Anthony',
  'Dwyane Wade',
  'Monta Ellis',
  'Kevin Martin',
  'Blake Griffin',
  2011],
 ['Kevin Durant',
  'LeBron James',
  'Kobe Bryant',
  'Russell Westbrook',
  'Kevin Love',
  'Blake Griffin',
  'Dirk Nowitzki',
  'Brandon Jennings',
  'Carmelo Anthony',
  'Josh Smith',
  2012],
 ['Kevin Durant',
  'Kobe Bryant',
  'LeBron James',
  'James Harden',
  'Carmelo Anthony',
  'Russell Westbrook',
  'Stephen Curry',
  'Monta Ellis',
  'Damian Lillard',
  'LaMarcus Aldridge',
  2013],
 ['Kevin Durant',
  'Carmelo Anthony',
  'LeBron James',
  'Kevin Love',
  'Blake Griffin',
  'Stephen Curry',
  'James Harden',
  'DeMar DeRozan',
  'Paul George',
  'Dirk Nowitzki',
  2014],
 ['James Harden',
  'Stephen Curry',
  'Russell Westbrook',
  'LeBron James',
  'Damian Lillard',
  'Klay Thompson',
  'LaMarcus Aldridge',
  'Anthony Davis',
  'Kyrie Irving',
  'Chris Paul',
  2015],
 ['James Harden',
  'Stephen Curry',
  'Kevin Durant',
  'LeBron James',
  'Damian Lillard',
  'Russell Westbrook',
  'Paul George',
  'DeMar DeRozan',
  'Isaiah Thomas',
  'Klay Thompson',
  2016],
 ['Russell Westbrook',
  'James Harden',
  'Isaiah Thomas',
  'Anthony Davis',
  'Damian Lillard',
  'DeMar DeRozan',
  'Stephen Curry',
  'LeBron James',
  'DeMarcus Cousins',
  2017],
 ['LeBron James',
  'James Harden',
  'Anthony Davis',
  'Russell Westbrook',
  'Giannis Antetokounmpo',
  'Damian Lillard',
  'Bradley Beal',
  'DeMar DeRozan',
  'Kevin Durant',
  'Lou Williams',
  2018],
 ['James Harden',
  'Paul George',
  'Kemba Walker',
  'Bradley Beal',
  'Damian Lillard',
  'Kevin Durant',
  'Giannis Antetokounmpo',
  'Stephen Curry',
  'Blake Griffin',
  2019],
 ['James Harden',
  'Damian Lillard',
  'Devin Booker',
  'Giannis Antetokounmpo',
  'Trae Young',
  'Bradley Beal',
  'LeBron James',
  'Donovan Mitchell',
  'Anthony Davis',
  2020],
 ['Stephen Curry',
  'Damian Lillard',
  'Bradley Beal',
  'Giannis Antetokounmpo',
  'Devin Booker',
  'Julius Randle',
  'Jayson Tatum',
  'Zion Williamson',
  2021],
 ['Trae Young',
  'DeMar DeRozan',
  'Joel Embiid',
  'Jayson Tatum',
  'Giannis Antetokounmpo',
  'Devin Booker',
  'Donovan Mitchell',
  2022]]

In [ ]:
#with open('ScoringAllByYearClean.pkl','wb') as f: #opens file
#  pickle.dump(scoringAllbyYearClean,f)

In [ ]:
tmpCarreer = playercareerstats.PlayerCareerStats(nbaIds['Jayson Tatum'])
nameTitle='Player_Name'
df = tmpCarreer.get_data_frames()[0]
df.insert(0,nameTitle,'Jayson Tatum')
#df['Player_Name'] = 'Jayson Tatum'
df

,Player_Name,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,Jayson Tatum,1628369,2017-18,00,1610612738,BOS,20.0,80,80,2443.0,...,0.826,50,352,402,128,83,58,114,170,1112
1,Jayson Tatum,1628369,2018-19,00,1610612738,BOS,21.0,79,79,2455.0,...,0.855,70,407,477,168,84,57,122,168,1243
2,Jayson Tatum,1628369,2019-20,00,1610612738,BOS,22.0,66,66,2265.0,...,0.812,64,396,460,200,93,57,155,136,1547
3,Jayson Tatum,1628369,2020-21,00,1610612738,BOS,23.0,64,64,2290.0,...,0.868,50,422,472,276,75,31,171,122,1692
4,Jayson Tatum,1628369,2021-22,00,1610612738,BOS,24.0,76,76,2731.0,...,0.853,85,524,609,334,75,49,217,174,2046
5,Jayson Tatum,1628369,2022-23,00,1610612738,BOS,25.0,74,74,2732.0,...,0.854,78,571,649,342,78,51,213,160,2225
6,Jayson Tatum,1628369,2023-24,00,1610612738,BOS,26.0,74,74,2645.0,...,0.833,67,534,601,364,75,43,188,145,1987

In [ ]:
len(df)
df.iloc[1]

Player_Name          Jayson Tatum
PLAYER_ID                 1628369
SEASON_ID                 2018-19
LEAGUE_ID                      00
TEAM_ID                1610612738
TEAM_ABBREVIATION             BOS
PLAYER_AGE                   21.0
GP                             79
GS                             79
MIN                        2455.0
FGM                           466
FGA                          1036
FG_PCT                       0.45
FG3M                          116
FG3A                          311
FG3_PCT                     0.373
FTM                           195
FTA                           228
FT_PCT                      0.855
OREB                           70
DREB                          407
REB                           477
AST                           168
STL                            84
BLK                            57
TOV                           122
PF                            168
PTS                          1243
Name: 1, dtype: object

In [ ]:
dfNeed = df2

In [ ]:
listOfYears =list()

In [ ]:
tmpYear1=2018
for key, value in df['SEASON_ID'].iteritems():
    #listOfYears.clear()
    print(key, value)
    if int(value[0:4]) == tmpYear1:
        print('YAY',key)
        ass = key
        if key not in listOfYears:
            listOfYears.append(ass)
print(listOfYears)

#dfass = pd.concat([df1,df['keys='])
    
# Choose entries with id p01
df_new = df[df['SEASON_ID'] == str("2018-19")]

0 2017-18
1 2018-19
YAY 1
2 2019-20
3 2020-21
4 2021-22
5 2022-23
6 2023-24
[1]

/var/folders/0y/bq7c7jv531171r938hd78kcc0000gn/T/ipykernel_24438/1501506676.py:2: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for key, value in df['SEASON_ID'].iteritems():

In [ ]:
df_new

,Player_Name,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
1,Jayson Tatum,1628369,2018-19,00,1610612738,BOS,21.0,79,79,2455.0,...,0.855,70,407,477,168,84,57,122,168,1243

In [390]:
scoringAllbyYearClean[7]

['Michael Jordan',
 'Alex English',
 'Dominique Wilkins',
 'Kiki Vandeweghe',
 'Larry Bird',
 'Mark Aguirre',
 'Dale Ellis',
 'Kevin McHale',
 'Tom Chambers',
 'Magic Johnson',
 1987]

In [337]:
tmpYear = 2018
tmpYear1= str(tmpYear)[2:]
tmpYear1= int(tmpYear1)+1
tmpYear=(str(tmpYear)+'-'+str(tmpYear1))
type(tmpYear)

str

In [ ]:
tmpCarreer = playercareerstats.PlayerCareerStats(nbaIds['Jaylen Brown'])
nameTitle='Player_Name'

df1 = tmpCarreer.get_data_frames()[0]
df1.insert(0,nameTitle,'Jaylen Brown')

#df['Player_Name'] = 'Jayson Tatum'
df1

In [325]:
with open('scoringAllbyYearClean.pkl', 'rb') as f:
    scoringAllbyYearClean = pickle.load(f) # deserialize using load()

In [338]:
mainDF

Empty DataFrame
Columns: [Player_Name, PLAYER_ID, SEASON_ID, LEAGUE_ID, TEAM_ID, TEAM_ABBREVIATION, PLAYER_AGE, GP, GS, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TOV, PF, PTS]
Index: []

[0 rows x 28 columns]

In [339]:
with open('scoringAllbyYearClean.pkl', 'rb') as f:
    scoringAllbyYearClean1 = pickle.load(f) # deserialize using load()
##### BY YEAR  STUFF
nameTitle='Player_Name'
for year in scoringAllbyYearClean1[0:2]:
    tmpYear = year[-1]
    tmpYear1= str(tmpYear)[2:]
    tmpYear1= int(tmpYear1)+1
    tmpYear=(str(tmpYear)+'-'+str(tmpYear1))
    year.pop()
    for name in year:
        #print(name)
        tmpCarreer = playercareerstats.PlayerCareerStats(nbaIds[name])
        df1 = tmpCarreer.get_data_frames()[0]
        df1.insert(0,nameTitle,name)
        df_new = df1[df1['SEASON_ID'] == tmpYear]
        mainDF = pd.concat([mainDF,df_new])

In [340]:
mainDF

,Player_Name,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
4,George Gervin,76804,1980-81,00,1610612759,SAN,29.0,82,NaN,2765.0,...,0.826,126.0,293.0,419,260,94.0,56.0,251.0,212,2221
6,Moses Malone,77449,1980-81,00,1610612745,HOU,26.0,80,80.0,3245.0,...,0.757,474.0,706.0,1180,141,83.0,150.0,308.0,223,2222
4,Julius Erving,76681,1980-81,00,1610612755,PHL,31.0,82,NaN,2874.0,...,0.787,244.0,413.0,657,364,173.0,147.0,266.0,233,2014
11,Kareem Abdul-Jabbar,76003,1980-81,00,1610612747,LAL,34.0,80,80.0,2976.0,...,0.766,197.0,624.0,821,272,59.0,228.0,249.0,244,2095
4,Dan Issel,77097,1980-81,00,1610612743,DEN,32.0,80,NaN,2641.0,...,0.759,229.0,447.0,676,158,83.0,53.0,130.0,249,1749
6,Adrian Dantley,76504,1980-81,00,1610612762,UTH,26.0,80,80.0,3417.0,...,0.806,192.0,317.0,509,322,109.0,18.0,282.0,245,2452
12,Elvin Hayes,76979,1980-81,00,1610612764,WAS,35.0,81,NaN,2931.0,...,0.617,235.0,554.0,789,98,68.0,171.0,189.0,300,1439
3,Otis Birdsong,76170,1980-81,00,1610612758,KCK,25.0,71,67.0,2593.0,...,0.697,119.0,139.0,258,233,93.0,18.0,173.0,172,1747
2,Mike Mitchell,77615,1980-81,00,1610612739,CLE,25.0,82,NaN,3194.0,...,0.784,215.0,287.0,502,139,63.0,52.0,175.0,199,2012
7,Adrian Dantley,76504,1981-82,00,1610612762,UTH,27.0,81,81.0,3222.0,...,0.792,231.0,283.0,514,324,95.0,14.0,299.0,252,2457
7,Moses Malone,77449,1981-82,00,1610612745,HOU,27.0,81,81.0,3398.0,...,0.762,558.0,630.0,1188,142,76.0,125.0,294.0,208,2520
5,George Gervin,76804,1981-82,00,1610612759,SAN,30.0,79,79.0,2817.0,...,0.864,138.0,254.0,392,187,77.0,45.0,210.0,215,2551
5,Julius Erving,76681,1981-82,00,1610612755,PHL,32.0,81,81.0,2789.0,...,0.763,220.0,337.0,557,319,161.0,141.0,214.0,229,1974
3,Mike Mitchell,77615,1981-82,00,1610612759,SAN,26.0,57,57.0,2090.0,...,0.733,173.0,276.0,449,43,33.0,28.0,98.0,200,1196
4,Mike Mitchell,77615,1981-82,00,1610612739,CLE,26.0,27,26.0,973.0,...,0.720,71.0,70.0,141,39,27.0,15.0,55.0,77,530
5,Mike Mitchell,77615,1981-82,00,0,TOT,26.0,84,83.0,3063.0,...,0.728,244.0,346.0,590,82,60.0,43.0,153.0,277,1726
5,David Thompson,78326,1981-82,00,1610612743,DEN,27.0,61,5.0,1246.0,...,0.814,57.0,91.0,148,117,34.0,29.0,142.0,149,906
7,Alex English,76673,1981-82,00,1610612743,DEN,28.0,82,82.0,3015.0,...,0.840,210.0,348.0,558,433,87.0,120.0,261.0,261,2082
7,Jamaal Wilkes,78532,1981-82,00,1610612747,LAL,29.0,82,82.0,2906.0,...,0.732,153.0,240.0,393,143,89.0,24.0,164.0,240,1734
4,Bernard King,77264,1981-82,00,1610612744,GOS,25.0,79,77.0,2861.0,...,0.705,140.0,329.0,469,282,78.0,23.0,267.0,285,1833

In [407]:
mainDF=df
mainDF= mainDF.drop([0,1,2,3,4,5,6])
mainDF

Empty DataFrame
Columns: [Player_Name, PLAYER_ID, SEASON_ID, LEAGUE_ID, TEAM_ID, TEAM_ABBREVIATION, PLAYER_AGE, GP, GS, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TOV, PF, PTS]
Index: []

[0 rows x 28 columns]

In [408]:
with open('scoringAllbyYearClean.pkl', 'rb') as f:
    scoringAllbyYearClean1 = pickle.load(f) # deserialize using load()
##### BY YEAR  STUFF
nameTitle='Player_Name'
for year in scoringAllbyYearClean1[0:4]:
    tmpYear = year[-1]
    tmpYear1= str(tmpYear)[2:]
    tmpYear1= int(tmpYear1)+1
    tmpYear=(str(tmpYear)+'-'+str(tmpYear1))
    year.pop()
    for name in year:
        #print(name)
        try:
            tmpCarreer = playercareerstats.PlayerCareerStats(nbaIds[name])
            df1 = tmpCarreer.get_data_frames()[0]
            df1.insert(0,nameTitle,name)
            df_new = df1[df1['SEASON_ID'] == tmpYear]
            mainDF = pd.concat([mainDF,df_new])
        except KeyError:
            pass

In [409]:
mainDF

,Player_Name,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
4,George Gervin,76804,1980-81,00,1610612759,SAN,29.0,82,NaN,2765.0,...,0.826,126.0,293.0,419,260,94.0,56.0,251.0,212,2221
6,Moses Malone,77449,1980-81,00,1610612745,HOU,26.0,80,80.0,3245.0,...,0.757,474.0,706.0,1180,141,83.0,150.0,308.0,223,2222
4,Julius Erving,76681,1980-81,00,1610612755,PHL,31.0,82,NaN,2874.0,...,0.787,244.0,413.0,657,364,173.0,147.0,266.0,233,2014
11,Kareem Abdul-Jabbar,76003,1980-81,00,1610612747,LAL,34.0,80,80.0,2976.0,...,0.766,197.0,624.0,821,272,59.0,228.0,249.0,244,2095
4,Dan Issel,77097,1980-81,00,1610612743,DEN,32.0,80,NaN,2641.0,...,0.759,229.0,447.0,676,158,83.0,53.0,130.0,249,1749
6,Adrian Dantley,76504,1980-81,00,1610612762,UTH,26.0,80,80.0,3417.0,...,0.806,192.0,317.0,509,322,109.0,18.0,282.0,245,2452
12,Elvin Hayes,76979,1980-81,00,1610612764,WAS,35.0,81,NaN,2931.0,...,0.617,235.0,554.0,789,98,68.0,171.0,189.0,300,1439
3,Otis Birdsong,76170,1980-81,00,1610612758,KCK,25.0,71,67.0,2593.0,...,0.697,119.0,139.0,258,233,93.0,18.0,173.0,172,1747
2,Mike Mitchell,77615,1980-81,00,1610612739,CLE,25.0,82,NaN,3194.0,...,0.784,215.0,287.0,502,139,63.0,52.0,175.0,199,2012
7,Adrian Dantley,76504,1981-82,00,1610612762,UTH,27.0,81,81.0,3222.0,...,0.792,231.0,283.0,514,324,95.0,14.0,299.0,252,2457
7,Moses Malone,77449,1981-82,00,1610612745,HOU,27.0,81,81.0,3398.0,...,0.762,558.0,630.0,1188,142,76.0,125.0,294.0,208,2520
5,George Gervin,76804,1981-82,00,1610612759,SAN,30.0,79,79.0,2817.0,...,0.864,138.0,254.0,392,187,77.0,45.0,210.0,215,2551
5,Julius Erving,76681,1981-82,00,1610612755,PHL,32.0,81,81.0,2789.0,...,0.763,220.0,337.0,557,319,161.0,141.0,214.0,229,1974
3,Mike Mitchell,77615,1981-82,00,1610612759,SAN,26.0,57,57.0,2090.0,...,0.733,173.0,276.0,449,43,33.0,28.0,98.0,200,1196
4,Mike Mitchell,77615,1981-82,00,1610612739,CLE,26.0,27,26.0,973.0,...,0.720,71.0,70.0,141,39,27.0,15.0,55.0,77,530
5,Mike Mitchell,77615,1981-82,00,0,TOT,26.0,84,83.0,3063.0,...,0.728,244.0,346.0,590,82,60.0,43.0,153.0,277,1726
5,David Thompson,78326,1981-82,00,1610612743,DEN,27.0,61,5.0,1246.0,...,0.814,57.0,91.0,148,117,34.0,29.0,142.0,149,906
7,Alex English,76673,1981-82,00,1610612743,DEN,28.0,82,82.0,3015.0,...,0.840,210.0,348.0,558,433,87.0,120.0,261.0,261,2082
7,Jamaal Wilkes,78532,1981-82,00,1610612747,LAL,29.0,82,82.0,2906.0,...,0.732,153.0,240.0,393,143,89.0,24.0,164.0,240,1734
4,Bernard King,77264,1981-82,00,1610612744,GOS,25.0,79,77.0,2861.0,...,0.705,140.0,329.0,469,282,78.0,23.0,267.0,285,1833
6,George Gervin,76804,1982-83,00,1610612759,SAN,31.0,78,78.0,2830.0,...,0.853,111.0,246.0,357,264,88.0,67.0,247.0,243,2043
8,Moses Malone,77449,1982-83,00,1610612755,PHL,28.0,78,78.0,2922.0,...,0.761,445.0,749.0,1194,101,89.0,157.0,264.0,206,1908
8,Adrian Dantley,76504,1982-83,00,1610612762,UTH,28.0,22,22.0,887.0,...,0.847,58.0,82.0,140,105,20.0,0.0,81.0,62,676
8,Alex English,76673,1982-83,00,1610612743,DEN,29.0,82,82.0,2988.0,...,0.829,263.0,338.0,601,397,116.0,126.0,263.0,235,2326
6,Julius Erving,76681,1982-83,00,1610612755,PHL,33.0,72,72.0,2421.0,...,0.759,173.0,318.0,491,263,112.0,131.0,196.0,202,1542
6,Gus Williams,78549,1982-83,00,1610612760,SEA,29.0,80,80.0,2761.0,...,0.751,72.0,133.0,205,643,182.0,26.0,230.0,117,1600
6,Dan Issel,77097,1982-83,00,1610612743,DEN,34.0,80,80.0,2431.0,...,0.835,151.0,445.0,596,223,83.0,43.0,174.0,227,1726
5,Bernard King,77264,1982-83,00,1610612752,NYK,26.0,68,68.0,2207.0,...,0.722,99.0,227.0,326,195,90.0,13.0,197.0,233,1486
9,Alex English,76673,1983-84,00,1610612743,DEN,30.0,82,77.0,2870.0,...,0.824,216.0,248.0,464,406,83.0,95.0,222.0,252,2167
3,Kiki Vandeweghe,78404,1983-84,00,1610612743,DEN,25.0,78,71.0,2734.0,...,0.852,84.0,289.0,373,238,53.0,50.0,156.0,187,2295
7,George Gervin,76804,1983-84,00,1610612759,SAN,32.0,76,76.0,2584.0,...,0.842,106.0,207.0,313,220,79.0,47.0,224.0,219,1967
2,Mark Aguirre,76016,1983-84,00,1610612742,DAL,24.0,79,79.0,2900.0,...,0.749,161.0,308.0,469,358,80.0,22.0,285.0,246,2330
5,Reggie Theus,78310,1983-84,00,1610612741,CHI,26.0,31,6.0,601.0,...,0.778,21.0,25.0,46,142,21.0,3.0,59.0,78,271
6,Reggie Theus,78310,1983-84,00,1610612758,KCK,26.0,30,29.0,897.0,...,0.751,29.0,54.0,83,210,29.0,9.0,97.0,93,474
7,Reggie Theus,78310,1983-84,00,0,TOT,26.0,61,35.0,1498.0,...,0.762,50.0,79.0,129,352,50.0,12.0,156.0,171,745
9,Moses Malone,77449,1983-84,00,1610612755,PHL,29.0,71,71.0,2613.0,...,0.750,352.0,598.0,950,96,71.0,110.0,250.0,188,1609
3,Joe Barry Carroll,76353,1983-84,00,1610612744,GOS,25.0,80,80.0,2962.0,...,0.723,235.0,401.0,636,198,103.0,142.0,268.0,244,1639
4,Larry Bird,1449,1983-84,00,1610612738,BOS,27.0,79,77.0,3028.0,...,0.888,181.0,615.0,796,520,144.0,69.0,237.0,197,1908
2,Isiah Thomas,78318,1983-84,00,1610612765,DET,23.0,82,82.0,3007.0,...,0.733,103.0,224.0,327,914,204.0,33.0,307.0,324,1748
4,Jim Paxson,77819,1983-84,00,1610612757,POR,26.0,81,81.0,2686.0,...,0.841,68.0,105.0,173,251,122.0,10.0,142.0,165,1722

In [410]:
#with open('scoringAllbyYearClean.pkl', 'rb') as f:
 #   scoringAllbyYearClean1 = pickle.load(f) # deserialize using load()
##### BY YEAR  STUFF
nameTitle='Player_Name'
for year in scoringAllbyYearClean1[5:10]:
    tmpYear = year[-1]
    tmpYear1= str(tmpYear)[2:]
    tmpYear1= int(tmpYear1)+1
    tmpYear=(str(tmpYear)+'-'+str(tmpYear1))
    year.pop()
    for name in year:
        #print(name)
        try:
            tmpCarreer = playercareerstats.PlayerCareerStats(nbaIds[name])
            df1 = tmpCarreer.get_data_frames()[0]
            df1.insert(0,nameTitle,name)
            df_new = df1[df1['SEASON_ID'] == tmpYear]
            mainDF = pd.concat([mainDF,df_new])
        except KeyError:
            pass

In [411]:
mainDF

,Player_Name,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
4,George Gervin,76804,1980-81,00,1610612759,SAN,29.0,82,NaN,2765.0,...,0.826,126.0,293.0,419,260,94.0,56.0,251.0,212,2221
6,Moses Malone,77449,1980-81,00,1610612745,HOU,26.0,80,80.0,3245.0,...,0.757,474.0,706.0,1180,141,83.0,150.0,308.0,223,2222
4,Julius Erving,76681,1980-81,00,1610612755,PHL,31.0,82,NaN,2874.0,...,0.787,244.0,413.0,657,364,173.0,147.0,266.0,233,2014
11,Kareem Abdul-Jabbar,76003,1980-81,00,1610612747,LAL,34.0,80,80.0,2976.0,...,0.766,197.0,624.0,821,272,59.0,228.0,249.0,244,2095
4,Dan Issel,77097,1980-81,00,1610612743,DEN,32.0,80,NaN,2641.0,...,0.759,229.0,447.0,676,158,83.0,53.0,130.0,249,1749
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9,Dominique Wilkins,1122,1991-92,00,1610612737,ATL,32.0,42,42.0,1601.0,...,0.835,103.0,192.0,295,158,52.0,24.0,122.0,77,1179
2,Tim Hardaway,896,1991-92,00,1610612744,GOS,25.0,81,81.0,3332.0,...,0.766,81.0,229.0,310,807,164.0,13.0,267.0,208,1893
4,Reggie Miller,397,1991-92,00,1610612754,IND,26.0,82,82.0,3120.0,...,0.858,82.0,236.0,318,314,105.0,26.0,157.0,210,1695
7,Charles Barkley,787,1991-92,00,1610612755,PHL,29.0,75,75.0,2881.0,...,0.695,271.0,559.0,830,308,136.0,44.0,235.0,196,1730
3,Mitch Richmond,782,1991-92,00,1610612758,SAC,27.0,80,80.0,3095.0,...,0.813,62.0,257.0,319,411,92.0,34.0,247.0,231,1803

In [412]:
#with open('scoringAllbyYearClean.pkl', 'rb') as f:
 #   scoringAllbyYearClean1 = pickle.load(f) # deserialize using load()
##### BY YEAR  STUFF
nameTitle='Player_Name'
for year in scoringAllbyYearClean1[11:15]:
    tmpYear = year[-1]
    tmpYear1= str(tmpYear)[2:]
    tmpYear1= int(tmpYear1)+1
    tmpYear=(str(tmpYear)+'-'+str(tmpYear1))
    year.pop()
    for name in year:
        #print(name)
        try:
            tmpCarreer = playercareerstats.PlayerCareerStats(nbaIds[name])
            df1 = tmpCarreer.get_data_frames()[0]
            df1.insert(0,nameTitle,name)
            df_new = df1[df1['SEASON_ID'] == tmpYear]
            mainDF = pd.concat([mainDF,df_new])
        except KeyError:
            pass

In [416]:
mainDF1 = mainDF

In [417]:
mainDF

,Player_Name,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
4,George Gervin,76804,1980-81,00,1610612759,SAN,29.0,82,NaN,2765.0,...,0.826,126.0,293.0,419,260,94.0,56.0,251.0,212,2221
6,Moses Malone,77449,1980-81,00,1610612745,HOU,26.0,80,80.0,3245.0,...,0.757,474.0,706.0,1180,141,83.0,150.0,308.0,223,2222
4,Julius Erving,76681,1980-81,00,1610612755,PHL,31.0,82,NaN,2874.0,...,0.787,244.0,413.0,657,364,173.0,147.0,266.0,233,2014
11,Kareem Abdul-Jabbar,76003,1980-81,00,1610612747,LAL,34.0,80,80.0,2976.0,...,0.766,197.0,624.0,821,272,59.0,228.0,249.0,244,2095
4,Dan Issel,77097,1980-81,00,1610612743,DEN,32.0,80,NaN,2641.0,...,0.759,229.0,447.0,676,158,83.0,53.0,130.0,249,1749
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8,Mitch Richmond,782,1996-97,00,1610612758,SAC,32.0,81,81.0,3115.0,...,0.861,59.0,260.0,319,338,118.0,24.0,237.0,211,2095
2,Juwan Howard,436,1996-97,00,1610612764,WAS,24.0,82,82.0,3318.0,...,0.756,202.0,450.0,652,311,93.0,23.0,246.0,259,1570
3,Anfernee Hardaway,358,1996-97,00,1610612753,ORL,25.0,59,59.0,2222.0,...,0.820,82.0,181.0,263,332,93.0,35.0,145.0,123,1210
3,Vin Baker,452,1996-97,00,1610612749,MIL,25.0,78,78.0,3156.0,...,0.687,267.0,537.0,804,211,81.0,112.0,245.0,275,1637
7,Glen Rice,779,1996-97,00,1610612766,CHH,30.0,79,78.0,3359.0,...,0.867,67.0,251.0,318,160,72.0,26.0,177.0,190,2115

In [434]:
with open('scoringAllbyYearClean.pkl', 'rb') as f:
    scoringAllbyYearClean1 = pickle.load(f) # deserialize using load()
##### BY YEAR  STUFF
nameTitle='Player_Name'
for year in scoringAllbyYearClean1[16:20]:
    tmpYear = year[-1]
    tmpYear1= str(tmpYear)[2:]
    tmpYear1= int(tmpYear1)+1
    tmpYear=(str(tmpYear)+'-'+str(tmpYear1))
    year.pop()
    for name in year:
        #print(name)
        try:
            tmpCarreer = playercareerstats.PlayerCareerStats(nbaIds[name])
            df1 = tmpCarreer.get_data_frames()[0]
            df1.insert(0,nameTitle,name)
            df_new = df1[df1['SEASON_ID'] == tmpYear]
            mainDF = pd.concat([mainDF,df_new])
        except KeyError:
            pass

In [430]:
#mainDF1 = mainDF
#scoringAllbyYearClean1[16:20]

In [450]:
#mainDF1 = mainDF
mainDF

,Player_Name,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
4,George Gervin,76804,1980-81,00,1610612759,SAN,29.0,82,NaN,2765.0,...,0.826,126.0,293.0,419,260,94.0,56.0,251.0,212,2221
6,Moses Malone,77449,1980-81,00,1610612745,HOU,26.0,80,80.0,3245.0,...,0.757,474.0,706.0,1180,141,83.0,150.0,308.0,223,2222
4,Julius Erving,76681,1980-81,00,1610612755,PHL,31.0,82,NaN,2874.0,...,0.787,244.0,413.0,657,364,173.0,147.0,266.0,233,2014
11,Kareem Abdul-Jabbar,76003,1980-81,00,1610612747,LAL,34.0,80,80.0,2976.0,...,0.766,197.0,624.0,821,272,59.0,228.0,249.0,244,2095
4,Dan Issel,77097,1980-81,00,1610612743,DEN,32.0,80,NaN,2641.0,...,0.759,229.0,447.0,676,158,83.0,53.0,130.0,249,1749
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,Russell Westbrook,201566,2013-14,00,1610612760,OKC,25.0,46,46.0,1412.0,...,0.826,55.0,208.0,263,319,88.0,7.0,177.0,104,1002
4,Stephen Curry,201939,2013-14,00,1610612744,GSW,26.0,78,78.0,2846.0,...,0.885,46.0,288.0,334,666,128.0,14.0,294.0,194,1873
10,Monta Ellis,101145,2013-14,00,1610612742,DAL,28.0,82,82.0,3023.0,...,0.788,38.0,257.0,295,471,141.0,23.0,264.0,197,1560
1,Damian Lillard,203081,2013-14,00,1610612757,POR,23.0,82,82.0,2937.0,...,0.871,35.0,253.0,288,457,64.0,22.0,193.0,197,1695
7,LaMarcus Aldridge,200746,2013-14,00,1610612757,POR,28.0,69,69.0,2499.0,...,0.822,166.0,599.0,765,178,63.0,68.0,123.0,147,1603

In [482]:
with open('scoringAllbyYearClean.pkl', 'rb') as f:
    scoringAllbyYearClean1 = pickle.load(f) # deserialize using load()
##### BY YEAR  STUFF
nameTitle='Player_Name'
for year in scoringAllbyYearClean1[21:25]:
    tmpYear = year[-1]
    tmpYear1= str(tmpYear)[2:]
    tmpYear1= int(tmpYear1)+1
    tmpYear=(str(tmpYear)+'-'+str(tmpYear1))
    year.pop()
    for name in year:
        #print(name)
        try:
            tmpCarreer = playercareerstats.PlayerCareerStats(nbaIds[name])
            df1 = tmpCarreer.get_data_frames()[0]
            df1.insert(0,nameTitle,name)
            df_new = df1[df1['SEASON_ID'] == tmpYear]
            mainDF = pd.concat([mainDF,df_new])
        except KeyError:
            pass

In [476]:
with open('scoringAllbyYearClean.pkl', 'rb') as f:
    scoringAllbyYearClean1 = pickle.load(f) # deserialize using load()

In [477]:
scoringAllbyYearClean1[21:25]

[['Kevin Garnett',
  'Tracy McGrady',
  'Paul Pierce',
  'Michael Redd',
  'Carmelo Anthony',
  'Dirk Nowitzki',
  'LeBron James',
  'Vince Carter',
  'Stephon Marbury',
  2004],
 ['Allen Iverson',
  'LeBron James',
  'Gilbert Arenas',
  'Dirk Nowitzki',
  'Tracy McGrady',
  'Vince Carter',
  'Ray Allen',
  'Dwyane Wade',
  'Kobe Bryant',
  2005],
 ['Kobe Bryant',
  'LeBron James',
  'Allen Iverson',
  'Gilbert Arenas',
  'Dirk Nowitzki',
  'Carmelo Anthony',
  'Paul Pierce',
  'Dwyane Wade',
  'Michael Redd',
  'Ray Allen',
  2006],
 ['Kobe Bryant',
  'LeBron James',
  'Gilbert Arenas',
  'Vince Carter',
  'Dirk Nowitzki',
  'Carmelo Anthony',
  'Ben Gordon',
  'Tracy McGrady',
  'Allen Iverson',
  'Kevin Garnett',
  2007]]

In [483]:
#mainDF = mainDF1
mainDF

,Player_Name,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
4,George Gervin,76804,1980-81,00,1610612759,SAN,29.0,82,NaN,2765.0,...,0.826,126.0,293.0,419,260,94.0,56.0,251.0,212,2221
6,Moses Malone,77449,1980-81,00,1610612745,HOU,26.0,80,80.0,3245.0,...,0.757,474.0,706.0,1180,141,83.0,150.0,308.0,223,2222
4,Julius Erving,76681,1980-81,00,1610612755,PHL,31.0,82,NaN,2874.0,...,0.787,244.0,413.0,657,364,173.0,147.0,266.0,233,2014
11,Kareem Abdul-Jabbar,76003,1980-81,00,1610612747,LAL,34.0,80,80.0,2976.0,...,0.766,197.0,624.0,821,272,59.0,228.0,249.0,244,2095
4,Dan Issel,77097,1980-81,00,1610612743,DEN,32.0,80,NaN,2641.0,...,0.759,229.0,447.0,676,158,83.0,53.0,130.0,249,1749
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,Russell Westbrook,201566,2013-14,00,1610612760,OKC,25.0,46,46.0,1412.0,...,0.826,55.0,208.0,263,319,88.0,7.0,177.0,104,1002
4,Stephen Curry,201939,2013-14,00,1610612744,GSW,26.0,78,78.0,2846.0,...,0.885,46.0,288.0,334,666,128.0,14.0,294.0,194,1873
10,Monta Ellis,101145,2013-14,00,1610612742,DAL,28.0,82,82.0,3023.0,...,0.788,38.0,257.0,295,471,141.0,23.0,264.0,197,1560
1,Damian Lillard,203081,2013-14,00,1610612757,POR,23.0,82,82.0,2937.0,...,0.871,35.0,253.0,288,457,64.0,22.0,193.0,197,1695
7,LaMarcus Aldridge,200746,2013-14,00,1610612757,POR,28.0,69,69.0,2499.0,...,0.822,166.0,599.0,765,178,63.0,68.0,123.0,147,1603

In [464]:
#with open('scoringAllbyYearClean.pkl', 'rb') as f:
 #   scoringAllbyYearClean1 = pickle.load(f) # deserialize using load()
##### BY YEAR  STUFF
nameTitle='Player_Name'
for year in scoringAllbyYearClean1[26:30]:
    tmpYear = year[-1]
    tmpYear1= str(tmpYear)[2:]
    tmpYear1= int(tmpYear1)+1
    tmpYear=(str(tmpYear)+'-'+str(tmpYear1))
    year.pop()
    for name in year:
        #print(name)
        try:
            tmpCarreer = playercareerstats.PlayerCareerStats(nbaIds[name])
            df1 = tmpCarreer.get_data_frames()[0]
            df1.insert(0,nameTitle,name)
            df_new = df1[df1['SEASON_ID'] == tmpYear]
            mainDF = pd.concat([mainDF,df_new])
        except KeyError:
            pass

In [465]:
mainDF

,Player_Name,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
4,George Gervin,76804,1980-81,00,1610612759,SAN,29.0,82,NaN,2765.0,...,0.826,126.0,293.0,419,260,94.0,56.0,251.0,212,2221
6,Moses Malone,77449,1980-81,00,1610612745,HOU,26.0,80,80.0,3245.0,...,0.757,474.0,706.0,1180,141,83.0,150.0,308.0,223,2222
4,Julius Erving,76681,1980-81,00,1610612755,PHL,31.0,82,NaN,2874.0,...,0.787,244.0,413.0,657,364,173.0,147.0,266.0,233,2014
11,Kareem Abdul-Jabbar,76003,1980-81,00,1610612747,LAL,34.0,80,80.0,2976.0,...,0.766,197.0,624.0,821,272,59.0,228.0,249.0,244,2095
4,Dan Issel,77097,1980-81,00,1610612743,DEN,32.0,80,NaN,2641.0,...,0.759,229.0,447.0,676,158,83.0,53.0,130.0,249,1749
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,Russell Westbrook,201566,2013-14,00,1610612760,OKC,25.0,46,46.0,1412.0,...,0.826,55.0,208.0,263,319,88.0,7.0,177.0,104,1002
4,Stephen Curry,201939,2013-14,00,1610612744,GSW,26.0,78,78.0,2846.0,...,0.885,46.0,288.0,334,666,128.0,14.0,294.0,194,1873
10,Monta Ellis,101145,2013-14,00,1610612742,DAL,28.0,82,82.0,3023.0,...,0.788,38.0,257.0,295,471,141.0,23.0,264.0,197,1560
1,Damian Lillard,203081,2013-14,00,1610612757,POR,23.0,82,82.0,2937.0,...,0.871,35.0,253.0,288,457,64.0,22.0,193.0,197,1695
7,LaMarcus Aldridge,200746,2013-14,00,1610612757,POR,28.0,69,69.0,2499.0,...,0.822,166.0,599.0,765,178,63.0,68.0,123.0,147,1603

In [457]:
#with open('scoringAllbyYearClean.pkl', 'rb') as f:
 #   scoringAllbyYearClean1 = pickle.load(f) # deserialize using load()
##### BY YEAR  STUFF
nameTitle='Player_Name'
for year in scoringAllbyYearClean1[31:34]:
    tmpYear = year[-1]
    tmpYear1= str(tmpYear)[2:]
    tmpYear1= int(tmpYear1)+1
    tmpYear=(str(tmpYear)+'-'+str(tmpYear1))
    year.pop()
    for name in year:
        #print(name)
        try:
            tmpCarreer = playercareerstats.PlayerCareerStats(nbaIds[name])
            df1 = tmpCarreer.get_data_frames()[0]
            df1.insert(0,nameTitle,name)
            df_new = df1[df1['SEASON_ID'] == tmpYear]
            mainDF = pd.concat([mainDF,df_new])
        except KeyError:
            pass

In [458]:
mainDF

,Player_Name,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
4,George Gervin,76804,1980-81,00,1610612759,SAN,29.0,82,NaN,2765.0,...,0.826,126.0,293.0,419,260,94.0,56.0,251.0,212,2221
6,Moses Malone,77449,1980-81,00,1610612745,HOU,26.0,80,80.0,3245.0,...,0.757,474.0,706.0,1180,141,83.0,150.0,308.0,223,2222
4,Julius Erving,76681,1980-81,00,1610612755,PHL,31.0,82,NaN,2874.0,...,0.787,244.0,413.0,657,364,173.0,147.0,266.0,233,2014
11,Kareem Abdul-Jabbar,76003,1980-81,00,1610612747,LAL,34.0,80,80.0,2976.0,...,0.766,197.0,624.0,821,272,59.0,228.0,249.0,244,2095
4,Dan Issel,77097,1980-81,00,1610612743,DEN,32.0,80,NaN,2641.0,...,0.759,229.0,447.0,676,158,83.0,53.0,130.0,249,1749
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,Damian Lillard,203081,2017-18,00,1610612757,POR,27.0,73,73.0,2670.0,...,0.916,62.0,263.0,325,481,77.0,27.0,206.0,117,1962
8,DeMar DeRozan,201942,2017-18,00,1610612761,TOR,28.0,80,80.0,2712.0,...,0.825,59.0,256.0,315,417,85.0,22.0,175.0,151,1840
8,Stephen Curry,201939,2017-18,00,1610612744,GSW,30.0,51,51.0,1631.0,...,0.921,36.0,225.0,261,310,80.0,8.0,153.0,114,1346
14,LeBron James,2544,2017-18,00,1610612739,CLE,33.0,82,82.0,3026.0,...,0.731,97.0,612.0,709,747,116.0,71.0,347.0,136,2251
9,DeMarcus Cousins,202326,2017-18,00,1610612740,NOP,27.0,48,48.0,1737.0,...,0.746,105.0,512.0,617,257,79.0,76.0,242.0,183,1210

In [459]:
#with open('scoringAllbyYearClean.pkl', 'rb') as f:
 #   scoringAllbyYearClean1 = pickle.load(f) # deserialize using load()
##### BY YEAR  STUFF
nameTitle='Player_Name'
for year in scoringAllbyYearClean1[35:38]:
    tmpYear = year[-1]
    tmpYear1= str(tmpYear)[2:]
    tmpYear1= int(tmpYear1)+1
    tmpYear=(str(tmpYear)+'-'+str(tmpYear1))
    year.pop()
    for name in year:
        #print(name)
        try:
            tmpCarreer = playercareerstats.PlayerCareerStats(nbaIds[name])
            df1 = tmpCarreer.get_data_frames()[0]
            df1.insert(0,nameTitle,name)
            df_new = df1[df1['SEASON_ID'] == tmpYear]
            mainDF = pd.concat([mainDF,df_new])
        except KeyError:
            pass

In [460]:
mainDF

,Player_Name,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
4,George Gervin,76804,1980-81,00,1610612759,SAN,29.0,82,NaN,2765.0,...,0.826,126.0,293.0,419,260,94.0,56.0,251.0,212,2221
6,Moses Malone,77449,1980-81,00,1610612745,HOU,26.0,80,80.0,3245.0,...,0.757,474.0,706.0,1180,141,83.0,150.0,308.0,223,2222
4,Julius Erving,76681,1980-81,00,1610612755,PHL,31.0,82,NaN,2874.0,...,0.787,244.0,413.0,657,364,173.0,147.0,266.0,233,2014
11,Kareem Abdul-Jabbar,76003,1980-81,00,1610612747,LAL,34.0,80,80.0,2976.0,...,0.766,197.0,624.0,821,272,59.0,228.0,249.0,244,2095
4,Dan Issel,77097,1980-81,00,1610612743,DEN,32.0,80,NaN,2641.0,...,0.759,229.0,447.0,676,158,83.0,53.0,130.0,249,1749
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9,Bradley Beal,203078,2021-22,00,1610612764,WAS,29.0,40,40.0,1439.0,...,0.833,38.0,151.0,189,265,36.0,15.0,135.0,95,928
8,Giannis Antetokounmpo,203507,2021-22,00,1610612749,MIL,27.0,67,67.0,2204.0,...,0.722,134.0,644.0,778,388,72.0,91.0,219.0,212,2002
6,Devin Booker,1626164,2021-22,00,1610612756,PHX,25.0,68,68.0,2345.0,...,0.868,45.0,297.0,342,329,77.0,26.0,162.0,180,1822
7,Julius Randle,203944,2021-22,00,1610612752,NYK,27.0,72,72.0,2544.0,...,0.756,125.0,591.0,716,370,53.0,39.0,245.0,205,1447
4,Jayson Tatum,1628369,2021-22,00,1610612738,BOS,24.0,76,76.0,2731.0,...,0.853,85.0,524.0,609,334,75.0,49.0,217.0,174,2046

In [461]:
mainDF2 = mainDF

In [480]:
mainDF2

,Player_Name,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
4,George Gervin,76804,1980-81,00,1610612759,SAN,29.0,82,NaN,2765.0,...,0.826,126.0,293.0,419,260,94.0,56.0,251.0,212,2221
6,Moses Malone,77449,1980-81,00,1610612745,HOU,26.0,80,80.0,3245.0,...,0.757,474.0,706.0,1180,141,83.0,150.0,308.0,223,2222
4,Julius Erving,76681,1980-81,00,1610612755,PHL,31.0,82,NaN,2874.0,...,0.787,244.0,413.0,657,364,173.0,147.0,266.0,233,2014
11,Kareem Abdul-Jabbar,76003,1980-81,00,1610612747,LAL,34.0,80,80.0,2976.0,...,0.766,197.0,624.0,821,272,59.0,228.0,249.0,244,2095
4,Dan Issel,77097,1980-81,00,1610612743,DEN,32.0,80,NaN,2641.0,...,0.759,229.0,447.0,676,158,83.0,53.0,130.0,249,1749
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9,Bradley Beal,203078,2021-22,00,1610612764,WAS,29.0,40,40.0,1439.0,...,0.833,38.0,151.0,189,265,36.0,15.0,135.0,95,928
8,Giannis Antetokounmpo,203507,2021-22,00,1610612749,MIL,27.0,67,67.0,2204.0,...,0.722,134.0,644.0,778,388,72.0,91.0,219.0,212,2002
6,Devin Booker,1626164,2021-22,00,1610612756,PHX,25.0,68,68.0,2345.0,...,0.868,45.0,297.0,342,329,77.0,26.0,162.0,180,1822
7,Julius Randle,203944,2021-22,00,1610612752,NYK,27.0,72,72.0,2544.0,...,0.756,125.0,591.0,716,370,53.0,39.0,245.0,205,1447
4,Jayson Tatum,1628369,2021-22,00,1610612738,BOS,24.0,76,76.0,2731.0,...,0.853,85.0,524.0,609,334,75.0,49.0,217.0,174,2046

In [481]:
#with open('mainScoringDFno20:25.pkl','wb') as f: #opens file
 #   pickle.dump(mainDF2,f)